maykinmedia/open-inwoner

.github/workflows/code-quality.yml, requirements/ci.txt, requirements/dev.in, requirements/dev.txt, src/open_inwoner/ckeditor5/views.py
https://github.com/PyCQA/bandit
=> Run bandit

src/open_inwoner/components/templates/components/Action/Actions.html
tasks:
* https://taiga.maykinmedia.nl/project/open-inwoner/task/541
* https://taiga.maykinmedia.nl/project/open-inwoner/task/504
* https://taiga.maykinmedia.nl/project/open-inwoner/task/503
=> small action list improvements

src/open_inwoner/accounts/forms.py
task - https://taiga.maykinmedia.nl/project/open-inwoner/task/502
I'm not sure should I change widget to 'autocomplete', I tried but it doesn't look like very beneficial, so I left the widget as it is
=> show full name instead of email for action users

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
tasks https://taiga.maykinmedia.nl/project/open-inwoner/task/672, https://taiga.maykinmedia.nl/project/open-inwoner/task/673
=> :arrow_up: bump django-digid-eherkenning to 0.3.3

src/open_inwoner/scss/components/Messages/_Message.scss
task - https://taiga.maykinmedia.nl/project/open-inwoner/task/445 (point 1)
=> :lipstick: swap colors of mine and other user's messages

src/open_inwoner/scss/components/Actions/Actions.scss, src/open_inwoner/scss/components/Card/LocationCardList.scss, src/open_inwoner/scss/components/Footer/Footer.scss, src/open_inwoner/scss/components/Form/Form.scss, src/open_inwoner/scss/components/Form/Input.scss, src/open_inwoner/scss/components/Form/MultiCheckbox.scss, src/open_inwoner/scss/components/Grid/Column.scss, src/open_inwoner/scss/components/Grid/Grid.scss, src/open_inwoner/scss/components/Notification/_Notification.scss
renamed grid-gap to gap. Since grid-gap is renamed to gap
=> Fixed the styling issue

src/open_inwoner/pdc/views.py, src/open_inwoner/scss/components/Header/AnchorMenu.scss
Disables sharing in products view
=> Disableshare

src/open_inwoner/accounts/forms.py, src/open_inwoner/accounts/tests/test_auth.py, src/open_inwoner/accounts/tests/test_contact_views.py, src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/accounts/views/contacts.py
I have also modified some queries concerning email in some places which I think they should exist for avoiding duplications in db. Let me know if you agree with that.
=> [#908] Feature/ability to modify email address

src/open_inwoner/components/templates/components/Form/ChoiceCheckbox.html
This is a fix based on the way we have implemented the init method of PlanForm. If you think we want to improve this by refactoring the related template tags I can create a new task-enhancement.
=> [#982] Issue/plan edit view with previous user

src/open_inwoner/scss/components/Form/Form.scss
Currently there is no pointer on hovering, that's why I just made this small change.
=> [#977] Fix/chevron styling in actions

src/open_inwoner/accounts/templates/registration/login.html
=> [#996] Fix/layout from admin to frontend

src/open_inwoner/accounts/forms.py, src/open_inwoner/accounts/models.py, src/open_inwoner/accounts/query.py, src/open_inwoner/accounts/templates/accounts/inbox.html, src/open_inwoner/accounts/templates/accounts/inbox_start.html, src/open_inwoner/accounts/tests/test_contact_views.py, src/open_inwoner/accounts/tests/test_file_upload.py, src/open_inwoner/accounts/tests/test_inbox_page.py, src/open_inwoner/accounts/tests/test_inbox_start_page.py, src/open_inwoner/accounts/tests/test_logging.py, src/open_inwoner/accounts/tests/test_message.py, src/open_inwoner/accounts/tests/test_message_query.py, src/open_inwoner/accounts/tests/test_notify_about_messages.py, src/open_inwoner/accounts/urls.py, src/open_inwoner/accounts/views/inbox.py, src/open_inwoner/components/templates/components/Messages/Messages.html, src/open_inwoner/components/templatetags/messages_tags.py, src/open_inwoner/components/templatetags/querystring_tags.py, src/open_inwoner/components/tests/test_messages.py, src/open_inwoner/scss/_fixes.scss, src/open_inwoner/scss/screen.scss
With "cleaned code" I mean I renamed all the `self.me` / `me`'s I ran into.
=> [#967] Refactored Inbox views to use user UUID, cleaned code

src/open_inwoner/accounts/views/cases.py, src/open_inwoner/openzaak/admin.py, src/open_inwoner/openzaak/managers.py, src/open_inwoner/openzaak/models.py, src/open_inwoner/openzaak/tests/test_admin.py, src/open_inwoner/openzaak/tests/test_case_detail.py, src/open_inwoner/scss/components/File/FileList.scss, src/open_inwoner/templates/pages/cases/status.html
I haven't found a specific design for this so I added just another section. If there is one somewhere else please let me know.
=> [#1046] Feature/add external url link to case detail

src/open_inwoner/openzaak/documents.py
This probably needs a backport to master.
=> [#1181] Update document API upload 'taal' to 'dut'

src/open_inwoner/accounts/views/cases.py, src/open_inwoner/openzaak/cases.py, src/open_inwoner/openzaak/documents.py
Some stuff got merged when I wasn't around to review so I'd fix it myself :wink:
=> Improved codestyle in case views and related code

src/open_inwoner/openzaak/auth.py
I edited this on the staging server but we'd want this always.
=> Added problematic notification JWT values to timeline log

src/open_inwoner/accounts/forms.py, src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/accounts/views/profile.py, src/open_inwoner/templates/pages/profile/edit.html
This is based on #499 which is not yet totally reviewed and merged.
=> [#1191] Add user image to the profile settings

src/open_inwoner/conf/base.py, src/open_inwoner/scss/components/Contacts/Contacts.scss, src/open_inwoner/templates/pages/profile/contacts/list.html
=> [#1159] Add profile image when accepting an invitation

src/open_inwoner/js/components/map/index.js, src/open_inwoner/pdc/models/product.py, src/open_inwoner/pdc/tests/test_product_location.py
=> [#1155] Link from map to location view

src/open_inwoner/templates/pages/cases/status.html
=> [#1128] Add icon to cases document upload button

src/open_inwoner/components/templates/components/AnchorMenu/AnchorMenu.html, src/open_inwoner/js/components/anchor-menu/index.js, src/open_inwoner/scss/components/Button/Button.scss, src/open_inwoner/scss/components/Header/AnchorMenu.scss
Issue for in-page anchors/links: https://taiga.maykinmedia.nl/project/open-inwoner/task/1198
Has to look like this on mobile (and not be sticky anymore):
=> :lipstick: [#1198] Mobile design: anchor/links styling

src/open_inwoner/templates/500.html
=> Updated error 500.html

src/open_inwoner/components/templates/components/Condition/ConditionList.html
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1194
Updated design with crosses: 
https://projects.invisionapp.com/share/UF134RWMWCK8#/screens/471522181
=> :lipstick: [#1194] Replace checkmark with cross for negative condition

src/open_inwoner/components/templates/components/AnchorMenu/AnchorMenu.html, src/open_inwoner/scss/components/Header/AnchorMenu.scss
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1240 
for Product pages only
=> :art: [#1240] Add 'Aanvraag starten' button in mobile anchor menu

src/open_inwoner/cms/products/urls.py, src/open_inwoner/pdc/tests/test_product.py
I made the mistake of cleaning some weird looking code that was actually needed.
=> [#1402] Fixed regression for reverse-URL issue with nested products

src/open_inwoner/conf/base.py, src/open_inwoner/custom_csp/middleware.py, src/open_inwoner/custom_csp/tests/test_csp.py
=> [#1404] Disable CSP when authenticated as staff user

src/open_inwoner/components/templates/components/Card/DescriptionCard.html, src/open_inwoner/components/templates/components/Card/ProductCard.html, src/open_inwoner/scss/components/Card/Card.scss, src/open_inwoner/scss/components/CardContainer/CardContainer.scss, src/open_inwoner/templates/cms/collaborate/active_plans_plugin.html, src/open_inwoner/templates/cms/products/categories_plugin.html, src/open_inwoner/templates/pages/user-home.html
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1334
All arrows need to be 'fixed' and aligned to the bottom of each (product/samenwerken)-Card.
So the arrow-position becomes independent from the description/content height of a card.
=> :lipstick: [#1334] Align arrows in cards to bottom

src/open_inwoner/components/templates/components/Card/DescriptionCard.html, src/open_inwoner/scss/components/Card/Card.scss, src/open_inwoner/scss/views/App.scss, src/open_inwoner/templates/cms/collaborate/active_plans_plugin.html, src/open_inwoner/templates/pages/cases/list.html
issue https://taiga.maykinmedia.nl/project/open-inwoner/task/1336 
extra: made plans-cards on homepage clickable
=> :lipstick: [#1336] Make bigger titles in all cards on all devices

src/open_inwoner/cms/tests/test_middleware.py, src/open_inwoner/cms/utils/middleware.py, src/open_inwoner/utils/tests/helpers.py
Also added tests and a mixin to improve 2FA testing
=> [#1452] Improved DropToolbarMiddleware to honour settings.TWO_FACTOR_FORCE_OTP_ADMIN

src/open_inwoner/scss/components/Header/AnchorMenu.scss, src/open_inwoner/scss/components/Header/Header.scss
- vertically center open/closed menu button
- set header to 100%
- decrease anchormenu padding
=> :lipstick: [#1451] Fix alignments in mobile productview

src/open_inwoner/apimock/apis/openklant-read/contactmomenten/contactmoment/aaaaaaaa-aaaa-aaaa-aaaa-bbbbbbbbbbb2.json, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/contactmoment/aaaaaaaa-aaaa-aaaa-aaaa-bbbbbbbbbbbb.json, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/klantcontactmomenten.json, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/klantcontactmomenten/aaaaaaaa-aaaa-aaaa-aaaa-ccccccccccc2.json, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/klantcontactmomenten/aaaaaaaa-aaaa-aaaa-aaaa-cccccccccccc.json, src/open_inwoner/apimock/apis/openklant-read/klanten/klant/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa.json, src/open_inwoner/apimock/apis/openklant-read/klanten/klanten.json, src/open_inwoner/apimock/tests/test_views.py, src/open_inwoner/apimock/urls.py, src/open_inwoner/apimock/views.py, src/open_inwoner/urls.py
With this you can define two Services (Klanten API and Contactmomenten API) and use them in the Open Klant Config.
Use the regular OAS files, and obv. replace scheme+host in the api-root:
API-root: http://localhost:8000/apimock/openklant-read/contactmomenten/
OAS: ./open_inwoner/openklant/tests/files/cmc.yaml
API-root: http://localhost:8000/apimock/openklant-read/klanten/
OAS: ./open_inwoner/openklant/tests/files/kc.yaml
=> [#1475] Added basic API mock-endpoint feature

src/open_inwoner/apimock/tests/test_views.py, src/open_inwoner/apimock/views.py
=> [#1475] Harden apimock against directory traversal

src/open_inwoner/components/templates/components/Header/Header.html, src/open_inwoner/scss/components/Form/Form.scss, src/open_inwoner/scss/components/Grid/Grid.scss, src/open_inwoner/scss/components/Header/Header.scss, src/open_inwoner/scss/components/Header/PrimaryNavigation.scss, src/open_inwoner/search/forms.py
=> :lipstick: [#1494] Fix margins and designs in mobile navigation

src/open_inwoner/js/components/map/index.js, src/open_inwoner/scss/components/Map/_leaflet.scss, src/open_inwoner/scss/components/Typography/Link.scss, src/open_inwoner/templates/pages/product/detail.html
Make link color in maps secundary color, but title needs to be black,
see https://taiga.maykinmedia.nl/project/open-inwoner/issue/1516
=> :lipstick: [#1516] Add secondary link styles to leaflet map

src/open_inwoner/scss/admin/_admin_theme.scss
https://taiga.maykinmedia.nl/project/open-inwoner/issue/1254
=> :lipstick: [#1254] Make Help tips in admin always show, without hover

src/open_inwoner/accounts/signals.py, src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/accounts/views/profile.py, src/open_inwoner/openklant/services.py, src/open_inwoner/openklant/tests/data.py, src/open_inwoner/openklant/tests/test_contactform.py, src/open_inwoner/openklant/tests/test_signal.py, src/open_inwoner/openklant/views/contactform.py, src/open_inwoner/utils/logentry.py, src/open_inwoner/utils/tests/helpers.py, src/open_inwoner/utils/tests/test_helpers.py, src/open_inwoner/utils/views.py
Also improved the logging for the earlier contact-api system logs. And cleaned up some f-strings from earlier.
=> [#1483] Update profile email/phone from klant on login

src/open_inwoner/scss/components/Button/Button.scss, src/open_inwoner/scss/components/Typography/H2.scss
https://taiga.maykinmedia.nl/project/open-inwoner/task/1543
via sprint 13: https://taiga.maykinmedia.nl/project/open-inwoner/us/1447
=> :lipstick: [#1543] Fixing margins for heading when CMS is in edit mode

src/open_inwoner/accounts/middleware.py
Taiga: [#1547](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1547)
=> [#1547] Fix digid logout

src/open_inwoner/accounts/tests/test_auth.py, src/open_inwoner/conf/base.py, src/open_inwoner/utils/validators.py
Added validator to check that passwords contain at least one upper-case letter, one lower-case letter, one digit.
Taiga: [#1562](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1562)
=> [#1562] Update password policy

src/open_inwoner/scss/components/Product/product-detail.scss, src/open_inwoner/scss/components/_index.scss, src/open_inwoner/templates/pages/product/detail.html
All grey lines need to be removed - except for the one between the content and the extra info - but... if there is no extra info, the line needs to not exist.
https://taiga.maykinmedia.nl/project/open-inwoner/task/1239
Note: because of changes in indentation, it's a bit difficult to review this in the file-changes-tab on Github, so view the raw file for proper blocks/conditions.
=> :art: [#1239] Making grey divider line conditional for product page

src/open_inwoner/cms/cases/tests/test_htmx.py, src/open_inwoner/utils/tests/helpers.py
Also upgraded the assertion of mock matchers called to a mixin
=> Fixed lingering problem in tests after merges of conflicting branches

src/open_inwoner/conf/base.py, src/open_inwoner/extended_sessions/middleware.py
Taiga: [#1561](https://taiga.maykinmedia.nl/project/open-inwoner/task/1561)
=> [#1561] make admin session cookie age configurable

src/open_inwoner/templates/pages/profile/actions/edit.html
Taiga: [#1638](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1638)
=> [#1638] fix template for creating/editing actions

src/open_inwoner/ssd/client.py, src/open_inwoner/ssd/templates/jaaropgave.html, src/open_inwoner/ssd/tests/test_xml_parsing.py, src/open_inwoner/ssd/xml.py
- Add missing translations of month names
=> clean up implementation of ssd

src/open_inwoner/scss/components/Header/Header.scss, src/open_inwoner/scss/views/_body.scss
https://taiga.maykinmedia.nl/project/open-inwoner/task/1678
=> :lipstick: [#1678] Correcting skipping behaviour of mobile login icon

src/open_inwoner/templates/pages/search.html
https://taiga.maykinmedia.nl/project/open-inwoner/task/1708
=> [#1708] Show search term in search page title

src/open_inwoner/scss/components/Video/Video.scss
issue https://taiga.maykinmedia.nl/project/open-inwoner/task/1756 branched off from issues #1713/#1714 (= PR #773 )
=> [#1756] Make video iFrames responsive

.github/workflows/ci.yml, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, src/open_inwoner/cms/cases/tests/test_htmx.py, src/open_inwoner/components/templates/components/Button/Button.html, src/open_inwoner/components/templates/components/Filter/Filter.html, src/open_inwoner/components/templates/components/Form/ChoiceCheckbox.html, src/open_inwoner/components/templates/components/Form/FormActions.html, src/open_inwoner/components/templates/components/Form/Input.html, src/open_inwoner/components/templates/components/Header/Header.html, src/open_inwoner/components/templatetags/button_tags.py, src/open_inwoner/components/templatetags/filter_tags.py, src/open_inwoner/components/templatetags/form_tags.py, src/open_inwoner/js/components/search/filter-mobile.js, src/open_inwoner/js/components/search/filter-options.js, src/open_inwoner/js/components/search/index.js, src/open_inwoner/scss/components/Form/Form.scss, src/open_inwoner/search/results.py, src/open_inwoner/search/tests/test_page.py, src/open_inwoner/search/views.py, src/open_inwoner/templates/master.html, src/open_inwoner/templates/pages/search.html, src/open_inwoner/utils/context_processors.py
https://taiga.maykinmedia.nl/project/open-inwoner/task/1707
=> [#1707] Remove double search bar from search page

src/open_inwoner/components/templates/components/Header/WarningHeader.html, src/open_inwoner/scss/components/WarningHeader/WarningHeader.scss
issue that was adjusted later: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1754
icon needs more spacing on desktop and mobile, and adding container width for neatness.
=> [#1754] Style icon in warning-banner

src/open_inwoner/cms/cases/views/cases.py
Taiga [#1832](https://taiga.maykinmedia.nl/project/open-inwoner/task/1832)
=> [#1832] Add breadcrumbs back to case list view

src/open_inwoner/openzaak/cases.py, src/open_inwoner/search/tests/test_views.py, src/open_inwoner/search/views.py
in case of exact match on identificatie
=> :sparkles: [#1802] Allow search for cases via searchbar

src/open_inwoner/ssd/client.py
Taiga [#1808](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1808)
=> [#1808] Use long month name for maandspecificatie PDF

src/open_inwoner/cms/cases/tests/test_contactform.py, src/open_inwoner/cms/cases/tests/test_htmx.py, src/open_inwoner/cms/cases/views/status.py, src/open_inwoner/openzaak/tests/test_case_detail.py
Taiga [#1827](https://taiga.maykinmedia.nl/project/open-inwoner/task/1827)
=> [#1827] Show second status for cases

src/open_inwoner/scss/components/Cases/Cases.scss, src/open_inwoner/templates/pages/cases/list_inner.html
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1831
correct grid/flex by bringing back previously deleted class.
=> :lipstick: [#1831] Add responsive style for cases in listview

src/open_inwoner/openzaak/notifications.py, src/open_inwoner/openzaak/tests/test_notification_zaak_status.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1904
=> :bug: [#1904] Fix status notification for duplicate configs

src/open_inwoner/search/views.py
Via https://github.com/maykinmedia/open-inwoner/security/code-scanning/12
=> Fixed Github codescanning warning 12 for 'URL redirection from remote source'

src/open_inwoner/openzaak/tests/test_utils.py, src/open_inwoner/openzaak/utils.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1919
=> :bug: [#1919] Do not show Zaken for Zaaktypes for which fetch fails

src/open_inwoner/cms/cases/views/status.py
Taiga [#1941](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1941)
This is a hotfix, not a proper solution. For discussion, cf. Taiga [#1942](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1942)
=> [#1941] Fix error on failed status type retrieval

src/open_inwoner/cms/products/cms_plugins.py, src/open_inwoner/cms/products/tests/test_plugin_categories.py, src/open_inwoner/cms/tests/cms_tools.py, src/open_inwoner/pdc/managers.py
~~based on https://github.com/maykinmedia/open-inwoner/pull/928, so that should be merged first~~
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1955
=> ✨ [#1955] Personalized onderwerpen for companies

src/open_inwoner/kvk/client.py, src/open_inwoner/kvk/signals.py, src/open_inwoner/kvk/tests/test_signals.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2014
=> :bug: [#2014] Fix retrieval of RSIN for KVK after login

Dockerfile
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2006
=> :whale: [#2006] Use apt-get upgrade in Dockerfile stage 3

src/open_inwoner/js/components/readmore/index.js, src/open_inwoner/scss/components/Header/AnchorMenu.scss, src/open_inwoner/scss/components/ReadMore/ReadMore.scss, src/open_inwoner/templates/pages/product/detail.html
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2005
=> 🐛 [#2005] Fix corrupted FAQ if readmore is inactive in product-pages

src/open_inwoner/kvk/tests/test_views.py, src/open_inwoner/kvk/views.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2000
=> :bug: [#2000] Fix infinite redirect if no company branches found

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Taiga [#1772](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1772)
=> [#1772] Upgrade django-log-outgoing-requests to 0.6.0

docker/openklant/fixtures/db.json, src/open_inwoner/accounts/views/contactmoments.py, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/objectcontactmomenten.json, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/objectcontactmomenten/aaaaaaaa-aaaa-aaaa-aaaa-dddddddddd2.json, src/open_inwoner/apimock/apis/openklant-read/contactmomenten/objectcontactmomenten/aaaaaaaa-aaaa-aaaa-aaaa-ddddddddddd.json, src/open_inwoner/components/templates/components/table/table.html, src/open_inwoner/components/templatetags/table_tags.py, src/open_inwoner/openklant/api_models.py, src/open_inwoner/openklant/tests/data.py, src/open_inwoner/openklant/tests/test_views.py, src/open_inwoner/openklant/wrap.py, src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss, src/open_inwoner/templates/pages/contactmoment/detail.html
task: https://taiga.maykinmedia.nl/project/open-inwoner/us/1992?no-milestone=1
=> :sparkles: [#1992] Link mijn vraag and aanvraag

src/open_inwoner/scss/components/Table/Tabled.scss, src/open_inwoner/templates/pages/profile/me.html, src/open_inwoner/templates/pages/profile/mydata.html
Preview the example in the Taiga issue here: http://localhost:8000/mijn-profiel/mydata/ with BRP login
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1989
=> [#1989] Fix grid for contact data

src/open_inwoner/accounts/views/contactmoments.py, src/open_inwoner/openklant/tests/test_views.py, src/open_inwoner/openklant/wrap.py, src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss, src/open_inwoner/templates/pages/contactmoment/list.html
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1861
=> :sparkles: [#1861] Show status in mijn vragen and use same design as aanvragen

src/open_inwoner/configurations/admin.py
Taiga [#2065](https://taiga.maykinmedia.nl/project/open-inwoner/task/2065)
=> [#2065] Fix typo ('SiteConfigurationAdmin' misspelled)

src/open_inwoner/accounts/templates/registration/login.html, src/open_inwoner/components/templates/components/Notification/Notification.html, src/open_inwoner/configurations/admin.py, src/open_inwoner/scss/components/Typography/wysiwyg.scss, src/open_inwoner/scss/components/_index.scss, src/open_inwoner/ssd/templates/jaaropgave.html, src/open_inwoner/ssd/templatetags/ssd_tags.py, src/open_inwoner/templates/pages/cases/status_inner.html, src/open_inwoner/utils/templatetags/utils.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1846
=> :sparkles: [#1846] Make login page text wysiwyg

src/open_inwoner/components/templates/components/Card/RenderCard.html, src/open_inwoner/scss/components/Card/Card.scss, src/open_inwoner/scss/components/Cases/CaseDetail.scss, src/open_inwoner/scss/components/Dashboard/Dashboard.scss, src/open_inwoner/scss/components/Form/FileInput.scss, src/open_inwoner/scss/components/List/_ListItem.scss, src/open_inwoner/scss/components/Status/_StatusList.scss, src/open_inwoner/scss/components/Table/Tabled.scss, src/open_inwoner/scss/components/UserFeed/UserFeed.scss, src/open_inwoner/scss/views/App.scss, src/open_inwoner/templates/pages/cases/list_inner.html, src/open_inwoner/templates/pages/profile/me.html
issue https://taiga.maykinmedia.nl/project/open-inwoner/task/1979 
Dates in case list were not put in the positions they needed to be, so now put conforming to design (closely aligned to the Case title) 
And: also improved some of the Card paddings according to design + changed the name of the gray variant to a "contextual" name that is more commonly used by designers and with design-tokens ('900' instead of '90').
Link to design: https://www.figma.com/file/iKGhWhstaLIlFSaND2q7cE/OIP---Designs-(new)?type=design&node-id=1%3A273&mode=design&t=PfzsswiRMAp5biaL-1
=> [#1979] Change date captions for cases list as design

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1913
=> :arrow_up: [#1913] Upgrade django-log-outgoing-requests to 0.6.1

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, src/open_inwoner/conf/base.py, src/open_inwoner/conf/local_example.py, src/open_inwoner/static/mailcss/email.css, src/open_inwoner/templates/mail/_base.html
Targets https://github.com/maykinmedia/open-inwoner/pull/999
Some stuff to bring the feature branch in shape. Jiro has the important bits so let's leave this draft so I could add some more on Friday.
- Moved some settings and set a default
- Requirements for updated with fixes to mail-editor
=> [#2059] More fixes for 'Add emailnotification templates' 

src/open_inwoner/components/templatetags/table_tags.py, src/open_inwoner/openklant/tests/data.py, src/open_inwoner/openklant/tests/test_views.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2103
=> 🐛 [#2103] Properly format eSuite zaakid in Mijn vraag

src/open_inwoner/conf/base.py
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2130\
after this is merged, I'll make PRs to default-project and OF
=> :lock: [#2130] Obfuscate incorrect password in Axes logs

src/open_inwoner/accounts/middleware.py, src/open_inwoner/accounts/templates/accounts/registration_necessary.html, src/open_inwoner/accounts/templates/registration/login.html, src/open_inwoner/accounts/tests/test_auth.py, src/open_inwoner/accounts/tests/test_oidc_views.py, src/open_inwoner/accounts/views/registration.py, src/open_inwoner/kvk/middleware.py
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1961
=> :bug: [#1961] Implement redirect after DigiD/eHerkenning OIDC login

requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt
This fixes the broken ckeditor and adds some updates and fixes to the mail-editor
=> [#2174] Updated ckeditor and mail-editor requirements

src/open_inwoner/js/components/form/FileInput.js, src/open_inwoner/scss/components/Form/FileInput.scss
Issue https://taiga.maykinmedia.nl/project/open-inwoner/task/2135 
Removing ending dot and improving text content for error texts, etc.
See also ongoing discussion in https://taiga.maykinmedia.nl/project/open-inwoner/task/1982
=> [#2135] Remove dots from file-upload errors

src/open_inwoner/components/templates/components/StatusIndicator/StatusIndicator.html, src/open_inwoner/scss/components/UserFeed/UserFeed.scss, src/open_inwoner/templates/cms/plugins/userfeed/userfeed.html
Issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2173
Should work when proper data is available,
I made the decision to still show a color banner in case there is no status_text set at all (also easier for the admin to spot if things need to be configured):
=> :lipstick: [#2173] Make userfeed indicators/icons conditional

src/open_inwoner/components/templates/components/Pagination/Pagination.html, src/open_inwoner/scss/components/Pagination/Pagination.scss
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2148
Concerns the design of pagination everywhere through the entire site.
=> :lipstick: [#2148] Make pagination conform to design

src/open_inwoner/apimock/apis/openklant-read/contactmomenten/objectcontactmomenten.json, src/open_inwoner/apimock/views.py
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2196
=> :clown_face: [#2196] Inject query parameter values in Mock API responses

src/open_inwoner/openklant/tests/test_contactform.py, src/open_inwoner/openklant/views/contactform.py
Taiga: [#2243](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2243)
=> [#2243] Remove subject from question card text

src/eherkenning/tests/test_mock_views.py, src/open_inwoner/accounts/eherkenning_urls.py, src/open_inwoner/accounts/tests/test_auth.py, src/open_inwoner/accounts/tests/test_oidc_views.py, src/open_inwoner/accounts/views/__init__.py, src/open_inwoner/accounts/views/auth.py, src/open_inwoner/urls.py
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2197
=> 🥅 [#2197] Block eHerkenning login for ZZP if RSIN is required

src/open_inwoner/js/components/card/ToggleHide.js, src/open_inwoner/templates/pages/cases/status_inner.html
Taiga: [#2254](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2254)
=> [#2254] Fix toggle hide for case-related questions

src/open_inwoner/accounts/middleware.py, src/open_inwoner/accounts/models.py, src/open_inwoner/accounts/query.py, src/open_inwoner/accounts/tests/factories.py, src/open_inwoner/accounts/tests/test_auth.py, src/open_inwoner/accounts/tests/test_user.py, src/open_inwoner/accounts/views/registration.py, src/open_inwoner/kvk/middleware.py, src/open_inwoner/kvk/views.py, src/open_inwoner/utils/middleware.py, src/open_inwoner/utils/tests/test_url.py, src/open_inwoner/utils/url.py
New attempt with less risky changes. This specifically replicates existing behavior. 
I tried refactoring the views that mess with `User.require_necessary_fields()` or otherwise do similar things to these middlewares but I had to revert & cherrypick twice so this is the simple version that just replaces the middlewares.
=>  [#2187] Refactored user update middleware

src/open_inwoner/templates/pages/profile/me.html
Taiga: [#2283](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2283)
=> [#2283] Show categories plugin even if no other plugin is enabled

src/open_inwoner/ssd/tests/test_views.py, src/open_inwoner/ssd/views.py
Taiga: [#2258](https://taiga.maykinmedia.nl/project/open-inwoner/task/2258)
=> [#2258] Add breadcrumbs to Mijn uitkeringen

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Taiga: [#2299](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2299)
=> [#2299] Upgrading django-digid-eherkenning and maykin-python-saml due to bug when parsing eHerkenning IdP metadata

src/open_inwoner/scss/components/Cases/CaseDetail.scss
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2275
=> :lipstick: [#2275] Fix margin document-notification

src/open_inwoner/scss/components/KCMSurvey/KCMSurvey.scss
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2311
=> :lipstick: [#2311] Add border around feedback button on mobile

src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/accounts/views/profile.py, src/open_inwoner/cms/plugins/cms_plugins/appointments.py, src/open_inwoner/cms/plugins/tests/test_appointments.py, src/open_inwoner/laposta/forms.py, src/open_inwoner/laposta/tests/test_forms.py, src/open_inwoner/qmatic/tests/data.py
=> [#2291 #2273 #2233] Use verified email for Laposta newsletters and Qmatic appointments

src/open_inwoner/utils/middleware.py
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2310
=> [#2310] Added `reverse("logout")` to user redirect middleware pass list

src/open_inwoner/accounts/tests/test_actions_expire.py, src/open_inwoner/accounts/tests/test_contact_views.py, src/open_inwoner/accounts/tests/test_notify_about_messages.py, src/open_inwoner/conf/parts/contact_approval.html, src/open_inwoner/conf/parts/expiring_action.html, src/open_inwoner/conf/parts/expiring_plan.html, src/open_inwoner/conf/parts/invite.html, src/open_inwoner/conf/parts/maileditor.py, src/open_inwoner/conf/parts/new_messages.html, src/open_inwoner/conf/parts/plan_action_update.html, src/open_inwoner/plans/tests/test_plans_expire.py, src/open_inwoner/plans/tests/test_views.py, src/open_inwoner/static/mailcss/email.css, src/open_inwoner/templates/mail/_base.html, src/open_inwoner/templates/pages/profile/contacts/list.html
Task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2255 
These 6 mailtemplates styled here:
http://127.0.0.1:8000/admin/mail_editor/mailtemplate/ >> Voorbeeld >> Open
These are only the mail-notifications meant for clients/inwoners.
contact_approval.html
expiring_action.html
expiring_plan.html
invite.html
new_messages.html
plan_action_update.html
=> :lipstick: [#2255] Add new mail-templates styles everywhere

src/open_inwoner/scss/components/Grid/Grid.scss
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2282
very minor issue :-)
=> :lipstick: [#2282] Remove box-shadow from welcome

src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/components/templatetags/helpers.py, src/open_inwoner/laposta/choices.py, src/open_inwoner/laposta/forms.py, src/open_inwoner/laposta/tests/test_forms.py, src/open_inwoner/scss/components/Form/ChoiceList.scss, src/open_inwoner/scss/components/Profile/_personal-overview.scss, src/open_inwoner/templates/pages/kvk/branches.html, src/open_inwoner/templates/pages/profile/me.html, src/open_inwoner/templates/pages/profile/notifications.html
Task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2289
➕ also corrected some odd mistakes in other code here and there.
=> :lipstick: [#2289] Add newsletter section checkbox styles

src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/templates/pages/profile/edit.html, src/open_inwoner/templates/pages/profile/me.html
Taiga: [#2248](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2248)
=> [#2248] Make contact details editable for eHerkenning user

src/open_inwoner/templates/pages/cases/list_outer.html, src/open_inwoner/templates/pages/cases/status_outer.html
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2378
=> :wheelchair: [#2378] Give spinner role for accessibility

src/open_inwoner/accounts/tests/test_profile_views.py, src/open_inwoner/templates/pages/profile/me.html
Taiga: [#2339](https://taiga.maykinmedia.nl/project/open-inwoner/task/2339)
=> [#2339] Fix display of name infix in profile

src/open_inwoner/accounts/templates/registration/login.html, src/open_inwoner/js/components/form/LoginForm.js, src/open_inwoner/js/components/tab-panels/index.js, src/open_inwoner/scss/components/TabPanel/TabPanel.scss
One very silly JS mistake, cleanup + attempt to clean up remnant leftovers from too many conditionals from the old login page, and added accessibility
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2389
=> :bug: [#2389] Activate Particulier Tab as default always

Dockerfile
Taiga: https://taiga.maykinmedia.nl/project/dimpact-enschede-ssc-ict-1/issue/81
=> Upgrade to Debian bookworm in Dockerfile

src/open_inwoner/conf/base.py
Taiga: [#2415](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2415)
=> [#2415] Update URL for PDOK Locatieserver

package-lock.json, package.json
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2481
=> :bug: [#2481] Correct OIP package version

.readthedocs.yaml
Taiga: [#2249](https://taiga.maykinmedia.nl/project/open-inwoner/task/2449)
Docs available at: https://docs.openinwoner.nl/en/latest/index.html
=> [#2249] Publish docs to Read The Docs

src/open_inwoner/__init__.py, src/open_inwoner/conf/base.py
I looked into pulling this from git but some installations like docker don't have a checkout so Alex agreed to keep using this method.
=> [#2510] Updated version number

src/open_inwoner/pdc/tests/test_views.py, src/open_inwoner/utils/ckeditor.py
Taiga: [#2465](https://taiga.maykinmedia.nl/project/open-inwoner/task/2465)
=> [#2465] Postprocess HTML for NLDS styling

Dockerfile, bin/check_celery_worker_liveness.py
Update docker file to support celery and add auto heal repair celery script for our health checks.
If you want flower I can add it. 
Might also want to update your docker-compose.yml.
=> Also add celery to docker containers, some ppl use them

src/open_inwoner/conf/base.py, src/open_inwoner/search/tasks.py, src/open_inwoner/search/tests/test_tasks.py
Taiga: [#2509](https://taiga.maykinmedia.nl/project/open-inwoner/task/2509)
=> [#2509] Create celery task to rebuild search index

src/open_inwoner/pdc/tests/test_product.py, src/open_inwoner/pdc/views.py
Taiga: [#2523](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2523)
=> [#2523] Prevent display of unpublished pages

src/open_inwoner/templates/pages/cases/statuses.html
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2349
=> :wheelchair: [#2349] Wrap headings around Case-status accordion buttons

src/open_inwoner/templates/pages/cases/statuses.html
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2350
=> ♿ [#2350] Remove link from status-accordion button

src/open_inwoner/scss/components/Status/_StatusList.scss, src/open_inwoner/templates/pages/cases/statuses.html
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2365
=> ♿ [#2365] Remove focus from final case status

package-lock.json, src/open_inwoner/js/components/accessibility/change_font.js, src/open_inwoner/js/components/accessibility/enlarge_font.js, src/open_inwoner/scss/components/AccessibilityHeader/AccessibilityHeader.scss, src/open_inwoner/scss/components/Header/Header.scss, src/open_inwoner/scss/components/Header/PrimaryNavigation.scss, src/open_inwoner/scss/components/Typography/H1.scss, src/open_inwoner/scss/components/Typography/H2.scss, src/open_inwoner/scss/components/Typography/H3.scss, src/open_inwoner/scss/components/Typography/H4.scss, src/open_inwoner/scss/views/App.scss
Also added font-enlarger
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2503
I am aware this looks very unattractive visually 😕 - specifically when both enlarging AND toggling the Dyslexia font...
=> [#2503] Add dyslexia modus with NL-DesignSystem components

src/open_inwoner/components/templates/components/File/File.html
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2366
=> ♿  [#2366] Add link purpose to document download links

requirements/base.txt, requirements/ci.txt, requirements/dev.txt
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2236
=> [#2236] Bump openformsclient to 0.4.0

src/open_inwoner/components/templates/components/Header/Header.html, src/open_inwoner/components/templates/components/Header/NavigationAuthenticated.html, src/open_inwoner/plans/tests/test_views.py
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2572
=> [#2572] Show roepnaam in log-in menu

src/open_inwoner/cms/cases/tests/test_contactform.py, src/open_inwoner/cms/cases/tests/test_htmx.py, src/open_inwoner/cms/cases/views/status.py, src/open_inwoner/openklant/clients.py
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2580
=> [#2580] Link questions with cases

docs/index.rst
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2620
=> [#2620] Update handbook for v 1.18

src/open_inwoner/openzaak/admin.py
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2637
=> [#2637] Support import/export of ZaakTypeConfig

src/open_inwoner/conf/base.py, src/open_inwoner/configurations/tasks.py, src/open_inwoner/configurations/tests/test_emails.py
=> [#2657] fix incorrect command invocation for failing mail digest task

src/open_inwoner/components/templates/components/FilterBar/MultiSelectListbox.html, src/open_inwoner/js/components/FilterBar/multiselect_listbox_checkbox.js, src/open_inwoner/scss/components/FilterBar/MultiSelectListbox.scss
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2783
Always show submit button when multiselect is opened
=> [#2783] Show submit button always when filter-bar opened

src/open_inwoner/templates/pages/cases/list_inner.html
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2776
=> [#2776] Show date modified instead of end date for openstaande aanvragen

src/open_inwoner/cms/cases/tests/test_contactform.py, src/open_inwoner/cms/cases/views/status.py
[Taiga #2800](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2800).
=> [#2800] Respect configured kanaal when registering contactmoment on zaak

src/open_inwoner/components/templates/components/Contact/ContactForm.html, src/open_inwoner/scss/components/Captcha/Captcha.scss
issues: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2829
in this PR only tackling the styling + proper associated HTML label tag.
=> :bug: [#2829] Fix captcha error-label styling

src/open_inwoner/js/components/accessibility/enlarge_font.js
issue https://taiga.maykinmedia.nl/project/open-inwoner/task/2367
dyslexia was already tackled in #1464 
So here only concentrating on correcting aria-label and title for enlargeFont toggle.
=> ♿  [#2367] Fix data-attributes for toggling larger font

src/open_inwoner/accounts/views/contactmoments.py, src/open_inwoner/openklant/constants.py, src/open_inwoner/openklant/models.py, src/open_inwoner/openklant/services.py, src/open_inwoner/openklant/tests/test_esuite_vragen_service.py, src/open_inwoner/openklant/tests/test_openklant2_service.py, src/open_inwoner/openklant/tests/test_views.py, src/open_inwoner/templates/pages/contactmoment/list.html
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2852
=> [#2852] Integrate OpenKlant2 service with list view
