maykinmedia/open-inwoner

src/open_inwoner/scss/admin/_ck_editor.scss

task - https://taiga.maykinmedia.nl/project/open-inwoner/task/614 
The toolbar is sticky by default, we just have to setup max height
CKEditor5 doesn't support AutoGrow plugin, so the easiest way to do it is with CSS.

:lipstick: set max-height for ck-editor

---

src/open_inwoner/pdc/resources/export_resource.py
src/open_inwoner/pdc/resources/import_resource.py

This has to do with a small update for keeping the m2m fields consistent. They are all imported and exported based on the slug field.

[#619] Update/product import-export fields

---

Dockerfile

Fixed MM internal #470 -- Ensuring correct mimetype is used for images, enabling DigiD Mock by default when using docker-compose

---

src/open_inwoner/accounts/urls.py
src/open_inwoner/accounts/views/cases.py
src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/tests/test_documents.py
src/open_inwoner/openzaak/tests/test_statuses.py

Continues from PR #327 & taiga 890

[#912] Harden access control on case-details/documents

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

There was some open-forms related code at module-level that tries to grab some data to fill some choices but it fails if the credentials aren't set, like on a fresh database.

Updated django-open-forms-client for slightly less noise and errors during startup/CI/manage.py

---

src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_documents.py

e-Suite doesn't support query on both zaak and BSN

[#948] Harden `fetch_roles_for_case_and_bsn()` to work with e-Suite

---

src/open_inwoner/plans/forms.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/templates/pages/plans/create.html

This was caused by custom widget template code doing an `in` operator, but the primary key of an object is an integer while the querydict has strings so it would never find the value.

[#899] Reselect template and contact on Plan-create validation error

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/conf/base.py
src/open_inwoner/openzaak/tests/factories.py

`zgw_consumers` 0.23.2 includes bugfix of `get_paginated_results` function, which should help with duplicated results (PR - https://github.com/maykinmedia/zgw-consumers/pull/58)
**NOTE!** 
`zgw_consumers` 0.21.0 has a breaking change - moving `Certificate` model into the separate library (https://github.com/maykinmedia/zgw-consumers/blob/main/CHANGELOG.rst#0210-2022-08-31)
After this PR is merged and deployed into staging the Open Zaak certificate configuration should be checked:
* requesting cases should work
* download documents should also work

#950 bump zgw-consumers to 0.23.2

---

src/open_inwoner/components/templates/components/table/table_cell.html
src/open_inwoner/scss/components/Table/Table.scss

After the styling of cases and statuses we added template tags for rendering tables in status. I saw that these template tags are being used only there that's why I changed only this part. @svenvandescheur  can provide his feedback about this.

[#956] Fix/remove tables' additional line

---

src/open_inwoner/accounts/tests/factories.py
src/open_inwoner/accounts/views/cases.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_case_request.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/openzaak/tests/test_cases_cache.py
src/open_inwoner/openzaak/tests/test_documents.py
src/open_inwoner/openzaak/tests/test_utils.py
src/open_inwoner/openzaak/utils.py

Note: the important change was to `is_zaak_visible()`
Then I found this wasn't applied to the list-views at all, and that required a refactor because we needed the filtering before the pagination which required to move the zaaktype retrieval code around.
But then I found the issue with the property casing in the mocks, and some other test noise like the cache-reset mixin and test data setup.
As a bonus: less noisy UserFactory, and improved ZGW api_model dataclass annotations that support swapping link URI's to objects because that is how it was used.

[#911] Added 'indicatieInternOfExtern' access check, also refactored cases-views tests

---

.github/workflows/code-quality.yml

This runs `manage.py makemigrations --check --dry-run` as part of the build, which will fail if there are changes in the model code that aren't part of the migrations up to this point.
So when you run makemigrations we won't have mystery migrations show up for code you didn't touch and have to decide if it was something important or just a label or choices change.
This also means a label change requires a migration.

Added Github workflow "Check for model changes not present in the migrations"

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/accounts/views/cases.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/catalog.py
src/open_inwoner/openzaak/managers.py
src/open_inwoner/openzaak/models.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/scss/components/File/FileList.scss
src/open_inwoner/templates/pages/cases/status.html

This has to do only with the upload form functionality, the refactoring after adding the ZaakType configs. 
The submission part is covered by the next task (taiga #1062).

[#1076] Fix/refactor case document upload form

---

src/open_inwoner/components/templates/components/Card/RenderCard.html

"As a visitor, I want to navigate through the entire product tile so that I can easily go to other pages.
Now only the image and title are clickable. Can the white part also be made clickable?"

:lipstick: [#1021] make entire card clickable

---

INSTALL.rst
src/open_inwoner/scss/components/Typography/H3.scss
src/open_inwoner/scss/components/Typography/H4.scss

Issue: on mobile view for locations, names/words break on all letters, instead of words.
(Both inside the headers of card-containers, as well in headers of leaflet map titles)
Note: "_While word-break: break-word is deprecated, it has the same effect, when specified, as word-break: normal and overflow-wrap: anywhere — regardless of the actual value of the [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) property._"

:lipstick: [#1082] Word/letter wrapping

---

src/open_inwoner/components/templates/components/Card/RenderCard.html

Reverts maykinmedia/open-inwoner#453
@jiromaykin ik was hiervoor iets te enthousiast door je draft-branch al te mergen, dus ik revert 'm voor nu:
Wees vrij om hiermee verder te gaan

Revert ":lipstick: [#1021] make entire card clickable"

---

src/open_inwoner/js/components/header/header.js
src/open_inwoner/scss/components/Header/Header.scss

Issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1121
Problem: propagation (bubbling) of events from the mobile menu into the dialog element that catches focus away from everything else.
**Notes for learning:**
Ways to inspect the constructor in file "_open_inwoner/js/components/abstract/component.js_":
`  constructor(node, initialState = {}) {
console.log('Component constructor', node, initialState) [.....]`
and
`  setState(changes) {
console.log('setState', changes) [.....]`
Ways to inspect the clickEvents in inspector: by using '[matches](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches)' in these 5 **console-logs** in file "_open_inwoner/js/components/header/header.js_":
1.
`  bindEvents() {
this.node.addEventListener('keyup', this.onKeyUp.bind(this)) …

:bug: [#1121] focus-trap in Header and Search

---

src/open_inwoner/components/templatetags/helpers.py
src/open_inwoner/plans/models.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/plans/views.py
src/open_inwoner/scss/components/Table/Table.scss
src/open_inwoner/templates/export/plans/plan_export.html
src/open_inwoner/templates/pages/plans/list.html

- Status column shows 'Open' (open plan) or 'Afgerond' (expired plan)
- Openstaande acties shows the number of 'open' actions (if status is 'open' or 'approval') with the proper message ('Actie vereist')

[#1109] Feature/update plan list view

---

src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/Faq/_Faq.scss
src/open_inwoner/scss/components/File/File.scss
src/open_inwoner/scss/components/Form/ButtonRadio.scss
src/open_inwoner/scss/components/Questionnaire/Questionnaire.scss
src/open_inwoner/scss/views/App.scss

Some borders need to be reverted to original design, because: The 'Toegankelijkheidsaudit' does not explicitly ask for borders around these areas + This Level AA requirement reads: "...Incidental: Text[...]that are part of an inactive user interface component, that are pure decoration,[...], have no contrast requirement..."
"pure decoration" in the definition of WCAG = "serving only an aesthetic purpose, providing no information, and having no functionality"
https://taiga.maykinmedia.nl/project/open-inwoner/task/1084
Answer to my question on Stack Overflow: https://stackoverflow.com/questions/75379770/do-borders-that-visually-group-related-content-have-a-contrast-requirement
“... WCAG does not require you to have a border around the grouped elements. […] there aren't any WCAG requirements …

:wheelchair: #1084 Check borders after accessibility changes

---

src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/scss/components/Logo/Logo.scss
src/open_inwoner/scss/views/App.scss

:wheelchair: [#1078] frontend a11y issues

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/accounts/views/cases.py
src/open_inwoner/openzaak/models.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/templates/pages/cases/status.html

This is changed in several places in case we already have created the singleton. Otherwise, the sorted version of the extensions is called when we create the instance for the first time.

[#1125] Fix/sort allowed file extensions in case document upload file

---

src/open_inwoner/components/templates/components/Footer/Footer.html
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
src/open_inwoner/scss/components/Footer/Footer.scss
src/open_inwoner/scss/components/Header/Header.scss

This is a draft because I hijacked @jiromaykin's ticket for the code change but there are some CSS considerations.

[#1057] Removed thumbnailer from header and footer logo

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

This has to wait for a bug fix in the library [(PR20).](https://github.com/maykinmedia/django-simple-certmanager/pull/20)

[#1137] Feature/update django simple cert manager to v1.3

---

src/open_inwoner/scss/components/Actions/Actions.scss
src/open_inwoner/scss/components/Typography/H1.scss
src/open_inwoner/scss/components/Typography/H2.scss

See issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1066
might not just be a problem on mobile but anywhere where text overflows;
words that are too long can be broken to the next line with a hyphen.
Note: `word-break: break-word` has been deprecated.

:art: [#1066] Wordwrapping on mobile

---

src/open_inwoner/scss/components/Dropdown/Dropdown.scss
src/open_inwoner/scss/components/File/File.scss

issue in Taiga: [#1131 Dropdown on mobile partly rendered off-screen](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1131)
In the original design it already showed the drop down should have been aligned to the right:
(https://projects.invisionapp.com/share/Y211V6JRHPC4#/screens/470665006)

:art: [#1131] Dropdown on mobile partly rendered off-screen

---

bin/generate_admin_index_fixture.sh
src/open_inwoner/conf/base.py

The first part fixes the discovery of fixtures, so you no longer need full path or extension.
The second part is a script `bin/generate_admin_index_fixture.sh` to manually run after we changed the admin-index, like after adding new models or links.
The third part adds a post-migrate signal handler so whenever `manage.py migrate` is run it will synchronize the admin-index so we're all looking at the same menu.
There is another level after this I didn't add for now, where we'd add a task to the CI workflow that fails if there are new models that aren't explicitly added or excluded from admin-index, but it can wait.

Fixed fixture discovery and added post-migrate admin-index fixture reloading

---

src/open_inwoner/components/templates/components/Header/AccessibilityHeader.html
src/open_inwoner/conf/locale/nl/LC_MESSAGES/django.po
src/open_inwoner/scss/components/Typography/H1.scss

Responsive design: fix issue where header text and button should be on top of each other, not next to each other;
see https://taiga.maykinmedia.nl/project/open-inwoner/task/1140 
⚠ Note: the current structure of templates, (where the entire H1 heading is surrounding the button), makes word-breaking behave strange again sometimes (causes letter-breaking in very long words on _very_ tiny screens).

:iphone: [#1140] mobile: Samenwerken-listview

---

src/open_inwoner/scss/components/Form/Form.scss

issue with overflowing UL's in registration view:
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/1139

:art: [#1139] login-screen validation-text

---

src/open_inwoner/templates/master.html

If we need it we can put it back, possibly add a fix that uses `request.csp_nonce` like the other script-tags.

Removed HTMX debug template-tag as it is not in active use and generates too much CSP noise

---

src/open_inwoner/js/components/autosumbit/index.js
src/open_inwoner/plans/forms.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/plans/views.py
src/open_inwoner/scss/components/Plan/PlanList.scss
src/open_inwoner/templates/pages/plans/list.html

FYI, we use auto-submit forms (via js) in some components. We have this for `input` and `select` html tags but afaik we only use it for select now, that's why I removed input selector. Another solution would be to add some time delay in order to be easier for the user to type something in the search input (before the form is auto-submitted).

[#1123] Feature/search functionality in plan list view

---

src/open_inwoner/utils/admin.py

This makes it easier to find/browse the type of logs we want to look at.

Added two list-filters to TimelineLog admin for better usability

---

src/open_inwoner/scss/components/Header/Breadcrumbs.scss

See task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1170

:lipstick: [#1170] Hide breadcrumbs on mobile

---

src/open_inwoner/components/templates/components/Card/CategoryCard.html
src/open_inwoner/components/templates/components/Card/RenderCard.html

See issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1168 
Theme/Category- cards need to be entirely clickable, unless they show Subthemes/Products.

:art: [#1168] Make Theme cards entirely clickable

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/components/templates/components/Footer/Footer.html
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Logo/Logo.html
src/open_inwoner/components/templates/components/Typography/Link.html
src/open_inwoner/components/templatetags/link_tags.py
src/open_inwoner/scss/components/Logo/Logo.scss

Note I had to update some dependencies to get SVG support in django-filer

[#1059] Added support for SVG logos

---

src/open_inwoner/components/templates/components/AnchorMenu/AnchorMenu.html
src/open_inwoner/js/components/anchor-menu/anchor-menu.js
src/open_inwoner/js/components/anchor-menu/index.js
src/open_inwoner/js/components/anchor-menu/scroll_to_top.js
src/open_inwoner/scss/components/Header/AnchorMenu.scss
src/open_inwoner/scss/views/_product_detail.scss
src/open_inwoner/templates/master.html

-make scroll-to-top appear everywhere on all mobile pages
-make it disappear when user is scrolled to top completely= make it appear only when scrolling down
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1180

:lipstick: [#1180] Make scroll-to-top anchor appear on every page

---

src/open_inwoner/scss/components/Container/Container.scss
src/open_inwoner/scss/components/Divider/Divider.scss
src/open_inwoner/scss/components/Footer/Footer.scss
src/open_inwoner/scss/components/Grid/Grid.scss
src/open_inwoner/scss/components/Notification/_Notification.scss

Fixing: in Footer and Productpages there is too much space on mobile when paragraphs/divs are empty, mostly because of Grid gap.
see: https://taiga.maykinmedia.nl/project/open-inwoner/task/1164

:lipstick: [#1164] Remove large space in footer and products on mobile

---

src/open_inwoner/scss/components/Container/Container.scss

This refers to the container that changed for mobiles and caused the `container--no-margin` to have margins outside of 'mobile first' styles: https://github.com/maykinmedia/open-inwoner/pull/525

:lipstick: [#1164] Fix extra margin space caused by PR #525

---

src/open_inwoner/accounts/templates/django_registration/registration_form.html
src/open_inwoner/components/templates/components/Action/Actions.html
src/open_inwoner/components/templatetags/form_tags.py
src/open_inwoner/scss/components/Autocomplete/Autocomplete.scss
src/open_inwoner/scss/components/Button/Button.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Form/GroupInput.scss
src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/scss/components/Messages/_Messages.scss
src/open_inwoner/scss/components/Table/Table.scss
src/open_inwoner/scss/components/Tags/TagList.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/plans/list.html
src/open_inwoner/templates/pages/profile/contacts/list.html
src/open_inwoner/templates/pages/search.html

Minor fixes, see Taiga issue 1179

:lipstick: [#1179] Add breakpoint for inputs, fix tags and other minor fixes

---

src/open_inwoner/accounts/templates/accounts/registration_necessary.html
src/open_inwoner/accounts/templates/django_registration/registration_form.html
src/open_inwoner/accounts/templates/registration/login.html
src/open_inwoner/pdc/views.py
src/open_inwoner/scss/components/CardContainer/CardContainer.scss
src/open_inwoner/scss/components/Header/AnchorMenu.scss
src/open_inwoner/scss/views/Categories.scss
src/open_inwoner/scss/views/Home.scss
src/open_inwoner/scss/views/_index.scss
src/open_inwoner/templates/pages/category/detail.html
src/open_inwoner/templates/pages/category/list.html
src/open_inwoner/templates/pages/home.html
src/open_inwoner/templates/pages/user-home.html

issue here: https://taiga.maykinmedia.nl/project/open-inwoner/task/1169 
This would solve the problem where 'icons' no longer look like this (with potentially cut-off heads): when the screensize gets smaller than the container - the only way to do this would be to set static sizes for the cards on all screenwidths, and inform the user which sizes need to be used for icons.
Note: this is not for images in Product cards.
ToDo:
other todo's to make the card align with design will be done later when decision is made about horizontal scroll and about the number of carsds in 1 column on mobile

:lipstick: [#1169] Make images/icons have static sizes in cards

---

src/open_inwoner/accounts/templates/registration/login.html
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/components/templates/components/Typography/Link.html
src/open_inwoner/components/templatetags/link_tags.py

Next is not used somewhere in the project (for instance if we click from an email the link to approve a contact we are not redirected to the contacts) so I added it for all the possible login methods.

[#1248] Redirect user to next after login

---

src/open_inwoner/components/templates/components/Card/CardContainer.html
src/open_inwoner/components/templates/components/Card/CategoryCard.html
src/open_inwoner/components/templates/components/Card/DescriptionCard.html
src/open_inwoner/components/templates/components/Card/ProductCard.html
src/open_inwoner/components/templates/components/Card/RenderCard.html
src/open_inwoner/components/templatetags/card_tags.py
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/List/_List.scss
src/open_inwoner/templates/pages/cases/list.html
src/open_inwoner/templates/pages/user-home.html

New clean branch for [old issue](https://github.com/maykinmedia/open-inwoner/pull/457).
Templates will need some more simplification, because currently they are not very maintainable.

:art: [#1021] Make entire Product card clickable

---

src/open_inwoner/components/templates/components/Header/Header.html

issue : https://taiga.maykinmedia.nl/project/open-inwoner/issue/1341
my mistake: `{% get_solo "configurations.SiteConfiguration" as config %}` was already put in in file,
and config needed to be put in the tag itself.

:art:  [#1341] Show cases in mobile menu

---

src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss
src/open_inwoner/scss/components/Typography/Link.scss
src/open_inwoner/templates/pages/product/detail.html

This fixes [https://taiga.maykinmedia.nl/project/open-inwoner/issue/1252](url) as well.

[#1326] Fix phonenumber, email and url in product location cards

---

src/open_inwoner/accounts/tests/test_file_upload.py
src/open_inwoner/accounts/tests/test_logging.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/accounts/urls.py
src/open_inwoner/accounts/views/__init__.py
src/open_inwoner/accounts/views/document.py
src/open_inwoner/accounts/views/documents.py
src/open_inwoner/plans/admin.py
src/open_inwoner/plans/forms.py
src/open_inwoner/plans/tests/test_logging.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/templates/pages/plans/create.html
src/open_inwoner/templates/pages/profile/me.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1234

[#1234] Remove file-upload from profile page

---

src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/urls.py
src/open_inwoner/accounts/views/__init__.py
src/open_inwoner/accounts/views/cases.py
src/open_inwoner/cms/cases/cms_apps.py
src/open_inwoner/cms/cases/urls.py
src/open_inwoner/cms/tests/urls.py
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/conf/base.py
src/open_inwoner/openzaak/notifications.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/openzaak/tests/test_cases_cache.py
src/open_inwoner/openzaak/tests/test_documents.py
src/open_inwoner/openzaak/tests/test_formapi.py
src/open_inwoner/openzaak/tests/test_notification_utils.py
src/open_inwoner/templates/pages/cases/list.html

I kept the views and tests at their current sub-optimal locations and basically moved the urls.
Most of the changes are because this changed the url namespace.
There are some issues that came up, like what to do when the page using the apphook is removed while other functionality depends on it (ex: without cases apphook the ZGW notifications have nowhere to link to).

First pass at moving 'Mijn Aanvragen' into a CMS apphook

---

src/open_inwoner/accounts/management/commands/notify_about_messages.py
src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/templates/accounts/inbox.html
src/open_inwoner/accounts/tests/test_admin.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_contact_views.py
src/open_inwoner/accounts/tests/test_file_upload.py
src/open_inwoner/accounts/tests/test_inbox_download_view.py
src/open_inwoner/accounts/tests/test_inbox_page.py
src/open_inwoner/accounts/tests/test_inbox_start_page.py
src/open_inwoner/accounts/tests/test_logging.py
src/open_inwoner/accounts/tests/test_notify_about_messages.py
src/open_inwoner/accounts/urls.py
src/open_inwoner/accounts/views/__init__.py
src/open_inwoner/accounts/views/inbox.py
src/open_inwoner/cms/inbox/cms_apps.py
src/open_inwoner/cms/inbox/urls.py
src/open_inwoner/cms/tests/urls.py
src/open_inwoner/components/readme.md
src/open_inwoner/components/templates/components/File/File.html
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/components/templates/components/Messages/Message.html
src/open_inwoner/components/templates/components/Messages/Messages.html
src/open_inwoner/components/templatetags/link_tags.py
src/open_inwoner/conf/base.py

Same as the other first-passes:
> I kept the views and tests at their current sub-optimal locations and basically moved the urls.
> 
> Most of the changes are because this changed the url namespace.

First pass at moving 'Mijn Berichten' into a CMS apphook

---

src/open_inwoner/accounts/tests/factories.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/cms/collaborate/cms_apps.py
src/open_inwoner/cms/collaborate/cms_plugins.py
src/open_inwoner/cms/collaborate/urls.py
src/open_inwoner/cms/tests/urls.py
src/open_inwoner/components/templates/components/Action/Actions.html
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/components/templatetags/action_tags.py
src/open_inwoner/conf/base.py
src/open_inwoner/configurations/models.py
src/open_inwoner/configurations/tests/test_help_modal.py
src/open_inwoner/configurations/tests/test_show_plans.py
src/open_inwoner/plans/management/commands/plans_expire.py
src/open_inwoner/plans/models.py
src/open_inwoner/plans/tests/test_logging.py
src/open_inwoner/plans/tests/test_plans_expire.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/plans/views.py
src/open_inwoner/templates/cms/collaborate/active_plans_plugin.html
src/open_inwoner/templates/pages/plans/detail.html
src/open_inwoner/templates/pages/plans/list.html
src/open_inwoner/templates/pages/user-home.html
src/open_inwoner/urls.py
src/open_inwoner/utils/tests/test_timeline_logger.py

Same as the other first-passes:
> I kept the views and tests at their current sub-optimal locations and basically moved the urls.
> 
> Most of the changes are because this changed the url namespace.

First pass at moving 'Samenwerken' into a CMS apphook

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/components/templates/components/Button/Button.html
src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/components/templates/components/Form/Form.html
src/open_inwoner/components/templatetags/form_tags.py
src/open_inwoner/js/components/index.js
src/open_inwoner/js/components/upload-document/file-input-errors.js
src/open_inwoner/js/components/upload-document/index.js
src/open_inwoner/js/components/upload-document/show-file-info.js
src/open_inwoner/scss/components/Form/DocumentUpload.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Header/AnchorMenu.scss
src/open_inwoner/scss/components/Notification/_Notifications.scss
src/open_inwoner/scss/components/Typography/P.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/scss/views/Home.scss
src/open_inwoner/templates/pages/cases/status.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1309 
multiple tasks:
other task:

:lipstick: [#1309] Make upload widget correspond with design

---

src/open_inwoner/components/templates/components/Header/Breadcrumbs.html
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/NavigationAuthenticated.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/components/templatetags/header_tags.py
src/open_inwoner/js/components/header/primary-navigation.js
src/open_inwoner/js/components/header/subpage-navigation.js
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss
src/open_inwoner/scss/components/Logo/Logo.scss
src/open_inwoner/scss/components/Typography/Link.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/cms/menu/primary.html

new mobile header designs + 2 new desktop menus:
https://projects.invisionapp.com/share/B3137YU0PZY2#/screens?browse 
In order to view the styles correctly for review: turn off the Django CMS-toolbar
(http://127.0.0.1:8000/?toolbar_off)
adds feature to issue mobile: https://taiga.maykinmedia.nl/project/open-inwoner/task/1378 
also adds feature to issue for desktop header: https://taiga.maykinmedia.nl/project/open-inwoner/task/1377
and adds feature to issue for indicator + dot: https://taiga.maykinmedia.nl/project/open-inwoner/task/1398
📲 Mobile menu:
Mobile menu works in all browsers the same
🖥️ Desktop menu:
🔔 Note:
NB: in Firefox desktop the Tab can't reach the submenu-items unless accessibility.tabfocus is set to number=7 in the about:config settings - which may be an issue on Mac …

:art: [#1378] Header multiple navigation (mobile and desktop)

---

src/open_inwoner/cms/utils/middleware.py
src/open_inwoner/conf/base.py

I tried a bunch of approaches, like putfing an if/else around the template tag, extending the regular ToolbarMiddleware, extending the template tag and some others, but this is the simplest that doesn't break anything.
It seems to work in browser, if it is acceptable I'll figure out how to create a test for this tomorrow.

[#1452] Added middleware to hide django-cms toolbar when not 2FA verified

---

src/open_inwoner/js/components/upload-document/show-file-info.js
src/open_inwoner/scss/components/Form/DocumentUpload.scss
src/open_inwoner/templates/pages/cases/status.html

Add a message that tells the user to re-upload the document after a validation error (when user forgets to enter a document-title).
See discussion: https://taiga.maykinmedia.nl/project/open-inwoner/task/1433 
(Having to re-upload is standard HTML behaviour)

:lipstick: [#1433] Add validation message for document upload

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/components/templates/components/Form/Form.html
src/open_inwoner/components/templatetags/form_tags.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/scss/components/Form/DocumentUpload.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/templates/pages/cases/status.html

:lipstick: [#1493] Improve document-upload style and texts

---

src/open_inwoner/components/templates/components/Header/NavigationAuthenticated.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/js/components/header/header.js
src/open_inwoner/js/components/header/primary-navigation.js
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss

- Click on the desktop menu to open, and click on the same menu to close
(make it work for both main menu and authenticated menu)
(while making Tab and Escape work)
Click outside desktop menu will also close it.

:lipstick: [#1495] Make desktop navigation toggle

---

src/open_inwoner/accounts/views/profile.py

[#1519] remove files from profile sidebar if files are empty

---

src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss
src/open_inwoner/scss/components/List/_List.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/templates/pages/contactmoment/list.html

Make entire card clickable, not just links.
Note: clickable Cards that are links themselves should not have any links inside - or else the HTML breaks.

:lipstick: [#1518] Make contactmoment card clickable

---

src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/NavigationAuthenticated.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/js/components/header/header.js
src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/scss/views/_body.scss

See if navigation can be fixed for old iPhones that cannot be updated anymore to use any iOS since 15.4
(in order to make dialog tag work)
solution: replace dialog tag  with div and change flexbox styles.
I have simplified javascript too - perhaps too simple this time? Needs review.

:bug: [#1467] Fix mobile navigation for old iOS devices

---

src/open_inwoner/js/components/confirmation/index.js

If the text is not set or if it is an empty string - do not make it render as "undefined" but rather as an empty string in the modal.

:bug: [#1523] Set empty confirmation text for file-deletion modal

---

src/open_inwoner/pdc/views.py
src/open_inwoner/templates/pages/product/form.html

Removed sidebar and form overview from the form template so that they are no longer displayed once a form has been started.
Taiga: #1509

[#1509] fix template 'form.html'

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

The upgrade should remove the intermediate screen shown when logging in via DigiD.
Taiga: 1505

[#1505] upgrade django-digid-eherkenning to 0.7.0

---

src/open_inwoner/scss/components/Form/DocumentUpload.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Notification/_Notifications.scss
src/open_inwoner/scss/components/Plan/PlanCreate.scss
src/open_inwoner/scss/components/Plan/PlanEdit.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/plans/create.html
src/open_inwoner/templates/pages/profile/actions/edit.html

Make the edit-plan/add-Action look like: 
https://projects.invisionapp.com/share/XP134RWRK3MG#/screens/471522253 
Also there is another page that has missing icons (Start nieuwe samenwerking):
https://projects.invisionapp.com/share/XP134RWRK3MG#/screens/471522250 
Note: due to adding extra class I had to change indentation of the templates.

:lipstick: [#1498] Add missing icons to plan-edit actions view

---

src/open_inwoner/scss/components/CardContainer/CardContainer.scss
src/open_inwoner/scss/views/Categories.scss

for screens wider than 1600 pixels set grid margins in such a way it will always show 4 cards next to each other.
https://taiga.maykinmedia.nl/project/open-inwoner/issue/1528
Note: **unfortunately it is not possible to use css variables INSIDE a media-query screen-width declaration:
"...The var() function can not be used as property names, selectors, or anything else besides property values. ..."**
Some standard screensizes to test this with:
1600 x 900 High Definition Plus (HD+)
1920 x 1080 Full High Definition (FHD)
1920 x 1200 Wide Ultra Extended Graphics Array (WUXGA)
2560 x 1440 Quad High Definition (QHD)
3440 x 1440 Wide Quad High Definition (WQHD)
3840 x 2160 4K or Ultra High Definition (UHD)

:lipstick: [#1528] Make cards responsive for very large desktop screens

---

src/open_inwoner/components/templates/components/Contact/ContactForm.html
src/open_inwoner/components/templatetags/contact_tags.py
src/open_inwoner/openklant/forms.py
src/open_inwoner/scss/components/ContactForm/ContactForm.scss
src/open_inwoner/scss/components/Form/Input.scss
src/open_inwoner/scss/components/Form/Select.scss
src/open_inwoner/scss/components/Form/Textarea.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/templates/pages/contactform/form.html

Contact form needs icon in select + different placeholder text, and styles for textarea.
https://projects.invisionapp.com/share/UF134RWMWCK8#/screens/471596624
In order to just change the Select styles, I needed to break open the form and turn it into a render_form.
Side Note: all Selects in the entire projects should 'actually' have a muted style, but it is impossible to do this with CSS if all fields have a value AND are not 'required' (or else all of the Options inside the Select will look muted) - **only required and invalid values can be targeted with CSS across most common browsers**.
"...The problem is that these elements have very different default looks across browsers, and while you can style them in some ways, some parts of their internals are literally impossible to style..." …

:lipstick: [#1529] Improve contact-form styles

---

src/open_inwoner/openklant/views/contactform.py

When both email and api are activated the success/error message is shown twice.

[#1553] Fix duplicate messages in contact form

---

src/open_inwoner/accounts/tests/test_action_views.py
src/open_inwoner/accounts/tests/test_inbox_page.py
src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/utils/tests/playwright.py

The generated classes don't work with parallel tests and have problems with decorators like requests mocker
We're going to move the multiple browser testing to a Github actions test matrix. This PR also prepares for that be exposing a. environment variable E2E_DRIVER and tagging the relevant tests with `@tag('e2e')`

Dropped multi_browser playwright testcase-generator decorator

---

src/open_inwoner/cms/cases/tests/test_contactform.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openklant/models.py
src/open_inwoner/scss/components/Cases/Cases.scss

FYI, currently we have the contact form in the case detail view but we only support sending a question via the api configuration. With this task we want to add the email configuration as well. 
It will be easier to review this if you take a look at [https://github.com/maykinmedia/open-inwoner/blob/develop/src/open_inwoner/openklant/views/contactform.py](url), where Bart had already implemented this for the basic contact form page.

[#1566] Add email registration to case detail contact form

---

src/open_inwoner/scss/components/Button/Button.scss
src/open_inwoner/scss/views/App.scss

set contrast to minimum of 4,5 to 1,0 (4,5:1)
https://taiga.maykinmedia.nl/project/open-inwoner/task/1613
can only be properly reviewed with "Web Developer" browser extension (=https://chrispederick.com/work/web-developer/) + any contrast-checker (like https://www.siegemedia.com/contrast-ratio).

:wheelchair: [#1613] Increasing color contrast in footer + scrollbutton

---

src/open_inwoner/js/components/questionnaire/index.js
src/open_inwoner/js/components/toggle/toggle.js
src/open_inwoner/scss/components/Faq/_Faq.scss
src/open_inwoner/scss/views/_body.scss

https://taiga.maykinmedia.nl/project/open-inwoner/task/1608
+ make mobile menu the **only Tabbable focus**, hide everything else 
+ make accordion FAQ titles the **only** focus on Tab key when collapsed/hidden; then again make accordion-panel focusable when answer is open, so user can tab towards links inside the panels.
info: the mobile 'view' will become visible when users zoom in more than 200% - hence why this needs to be accessible with keyboard tabs as well.

:wheelchair: [#1608] Setting up focus trap for accordion and mobile menu

---

src/open_inwoner/components/templates/components/Action/ActionStatusButton.html
src/open_inwoner/components/templates/components/Action/Actions.html
src/open_inwoner/components/templates/components/Dropdown/Dropdown.html
src/open_inwoner/scss/components/Actions/Actions.scss
src/open_inwoner/scss/components/Dropdown/Dropdown.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Plan/PlanCreate.scss
src/open_inwoner/scss/components/Preview/Preview.scss
src/open_inwoner/templates/pages/profile/categories.html
src/open_inwoner/templates/pages/profile/contacts/list.html

https://taiga.maykinmedia.nl/project/open-inwoner/issue/1594

:lipstick: [#1594] Improving onderwerp selection and dropdowns

---

src/open_inwoner/components/templates/components/Faq/Faq.html
src/open_inwoner/components/templates/components/Step/StepIndicator.html
src/open_inwoner/js/components/dropdown/index.js
src/open_inwoner/scss/components/Faq/_Faq.scss
src/open_inwoner/scss/views/_accessibility.scss
src/open_inwoner/scss/views/_index.scss

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1598
Note to self:
HTML `<li>` tags do not necessarily need an aria-label attribute to indicate that they are the current step in a step-indicator. Instead, you can use the aria-current attribute with the value of "step" to convey the current state. The aria-label attribute, in this case, is not required.
When a screen reader encounters an element with an aria-label attribute, it will read out the content of the aria-label attribute. However, it's important to note that screen readers typically **prioritize the accessible name of an element**. The accessible name is determined by various factors, including the element's text content and associated labels
....screen readers will typically read out both the content of the list …

:wheelchair: [#1598] Improving accessibility relational information

---

src/open_inwoner/components/templates/components/Button/Button.html
src/open_inwoner/components/templates/components/Dropdown/Dropdown.html
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/js/components/dropdown/index.js
src/open_inwoner/js/components/header/header.js
src/open_inwoner/js/components/header/subpage-navigation.js

issue https://taiga.maykinmedia.nl/project/open-inwoner/task/1611
The aria-expanded attribute has to be applied to the focusable, interactive control that toggles the visibility of the object - needs to be set to False initially because everything starts off in a closed state.
Also: corrects this for the dropdown... where I set the aria-expanded attribute to the wrong node.
This will set this attribute to these 2 toggle menus (3 & 4):
The aria-expanded attribute should NOT be added to the desktop menus (1 & 2),
because they need to be continuously accessible with the Tab keys: so their state is not 'invisible' for screenreaders (even though they are invisible for people that can see).:

:wheelchair: [#1611] Improving robust mobile menus with aria-expanded

---

src/open_inwoner/components/templates/components/Header/Header.html

A template variable was erroneously renamed in a previous PR.
Taiga: [#1686](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1686)

[#1686] rename template variable

---

src/open_inwoner/accounts/signals.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/haalcentraal/api_models.py
src/open_inwoner/haalcentraal/signals.py
src/open_inwoner/haalcentraal/tests/files/ingeschrevenpersonen.999993847_2.0.json
src/open_inwoner/haalcentraal/tests/files/personen_2.0.yaml
src/open_inwoner/haalcentraal/tests/test_logging.py
src/open_inwoner/haalcentraal/utils.py
src/open_inwoner/templates/pages/profile/mydata.html

The refactoring and update commits are split for convenience.

[#1536] Refactored Haalcentraal to use a dataclass and update to 2.0-final

---

src/open_inwoner/scss/components/CookieConsent/CookieBanner.scss

in order to test/review this: if you have previously clicked on the cookiebanner (making it invisible), you can make it appear in your browser again by looking in your Dev Tools for an >> Application >> Cookies/Local Storage tab and delete the "cookieBannerAccepted" cookie, or in >> Storage Tab >> Cookies >> localhost and remove "cookieBannerAccepted" (usually delete cookies via right-click)
https://taiga.maykinmedia.nl/project/open-inwoner/task/1677

💄 [#1677] Making cookiebanner margins and modal same on mobile

---

src/open_inwoner/scss/components/Spinner/Spinner.scss
src/open_inwoner/templates/pages/cases/list_outer.html
src/open_inwoner/templates/pages/cases/status_outer.html

https://taiga.maykinmedia.nl/project/open-inwoner/task/1662

:lipstick: [#1649] Improving spinner styling

---

src/open_inwoner/accounts/tests/test_profile_views.py

A variable was renamed in the main code but not in the test during the recent Haalcentral refactor

rename variable in test

---

src/open_inwoner/cms/extensions/cms_menus.py
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/NavigationAuthenticated.html
src/open_inwoner/components/templatetags/header_tags.py
src/open_inwoner/templates/master.html

As workaround for menu-indicators issue & context pollution.
Also dropped the `header` template tag :tada:

[#1492] Capture django-cms menu output and re-use, as workaround for menu-indicators issue & context pollution

---

src/open_inwoner/cms/extensions/cms_menus.py
src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/components/templates/components/Header/NavigationAuthenticated.html
src/open_inwoner/components/templates/components/Header/PrimaryNavigation.html
src/open_inwoner/components/templatetags/header_tags.py
src/open_inwoner/pdc/tests/test_category.py
src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/templates/master.html

https://taiga.maykinmedia.nl/project/open-inwoner/task/1492
show just a dot IF there are any notifications for messages OR plans.
we do not have a design for this so I just made it look like this (dot has the same size as the other one and overlaps the down-arrow a bit):

:lipstick: [#1492] Adding notification dot in login menu

---

src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss

Login button on the right (on desktop) should be aligned to right-side of container, even when Onderwerpen are made invisible.
https://taiga.maykinmedia.nl/project/open-inwoner/task/1690

:lipstick: [#1690] Aligned authenticated- and login nav buttons

---

src/open_inwoner/components/templates/components/AnchorMenu/AnchorMenu.html
src/open_inwoner/js/components/anchor-menu/anchor-menu.js
src/open_inwoner/pdc/tests/test_product.py
src/open_inwoner/pdc/utils.py
src/open_inwoner/pdc/views.py
src/open_inwoner/scss/components/Header/AnchorMenu.scss
src/open_inwoner/utils/ckeditor.py

- add subheadings to product page sidebar
- remove anchors for 'links' and 'see further' ('zie ook') 
Taiga: [#1535](https://taiga.maykinmedia.nl/project/open-inwoner/task/1535)

[#1535] Added subheading anchors to product page sidebar

---

src/open_inwoner/components/templates/components/Header/Header.html
src/open_inwoner/scss/components/Header/Header.scss

Self-identified problem: https://taiga.maykinmedia.nl/project/open-inwoner/task/1717
This needed restructering in the mobile menu in order to push elements to their initial positions.

[#1717] Make warningbanner not overlap opened mobile menu

---

src/open_inwoner/js/components/search/index.js

https://taiga.maykinmedia.nl/project/open-inwoner/issue/1739
+ Preferably use '`let` 'instead of '`var`' for scope
+ Replaced `setInterval` with `setTimeout` to avoid continuous looping. Code inside setTimeout will execute once after the specified delay (250 milliseconds) 
+ Setting `timerId` to null instead of zero is a common practice in JavaScript when using variables to represent timers or intervals + makes it clear that the timerId variable is not currently associated with any active timer - a way to indicate that there is no ongoing timer operation.

[#1739] :bug: Fix infinite loop for search page filters

---

src/open_inwoner/scss/components/CookieConsent/CookieBanner.scss

This issue only occurs on mobile devices (margins on desktop are not affected by scroll or size of URL bar)
PR can only be reviewed on mobile devices, so either use Gronk or use Browserstack.
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1735

[#1735] Fix cookiebanner position for mobile devices

---

src/open_inwoner/search/tests/test_feedback.py
src/open_inwoner/search/tests/test_page.py
src/open_inwoner/search/views.py
src/open_inwoner/templates/pages/search.html

https://taiga.maykinmedia.nl/project/open-inwoner/task/1709

[#1709] Add info for when there are zero search results

---

src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/templates/registration/password_change_done.html
src/open_inwoner/templates/registration/password_change_form.html
src/open_inwoner/templates/registration/password_reset_complete.html
src/open_inwoner/templates/registration/password_reset_confirm.html
src/open_inwoner/templates/registration/password_reset_done.html
src/open_inwoner/templates/registration/password_reset_email.html
src/open_inwoner/templates/registration/password_reset_form.html
src/open_inwoner/templates/registration/password_reset_subject.txt

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1732
New file `password_reset_subject.txt` added here:
https://github.com/maykinmedia/open-inwoner/pull/771/files#diff-01d2a103e38c25a357a69204ee48bb109142c26b3da6271f5ac3f1ba94e33725
also connected to the translations issue where we're keeping track of English defaults, instead of Dutch in the code
(anything that is now called 'Wachtwoordherinitialisatie' shall later be renamed to B1 'Wachtwoordwijziging')

[#1732] Make password-reset subject translatable

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/conf/base.py
src/open_inwoner/setup.py

Taiga [#1744](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1744)

[#1744] Added timeouts to requests

---

src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_user.py

Ability to change this centrally shows why DRY code (like a method) is preferred over spreading ad-hoc code.

[#1701] Changed User.get_full_name() to prefer .display_name over .first_name

---

src/open_inwoner/accounts/management/commands/delete_invitations.py
src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_commands.py
src/open_inwoner/conf/base.py
src/open_inwoner/utils/logentry.py

Taiga [#1715](https://taiga.maykinmedia.nl/project/open-inwoner/task/1715)

[#1715] Added management command to delete expired contact invitations

---

src/open_inwoner/scss/components/Feedback/Feedback.scss
src/open_inwoner/templates/pages/search.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1779
needs filled sidebar or else checkboxes will align weirdly

[#1779] Fix alignment of search results

---

src/open_inwoner/ssd/xml.py

Taiga [#1805](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1805)
The bug is caused by incorrect use of `lxml.fromstring`, which returns an lxml element instead of the document tree, in contrast to `lxml.parse` which was used to read in the content of the file object during testing.

[#1805] Fix xml error

---

src/open_inwoner/pdc/tests/test_views.py
src/open_inwoner/pdc/views.py

Taiga [#1804](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1804)

[#1804] Fix missing category 500

---

Dockerfile

upgrading FontAwesome caused dependency issues

:whale: Fix NPM install in Docker

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1733
NPM keeps on hanging on 6.1.1 but needs to become 6.4.2 everywhere
`npm install --save @fortawesome/free-brands-svg-icons --force`
or:
`npm ci --legacy-peer-deps`

[#1733] Product sharing X icon

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/conf/base.py

Taiga [#1773](https://taiga.maykinmedia.nl/project/open-inwoner/task/1773)

[#1773] Bumped log-outgoing-requests and added setting for deleting logs

---

src/open_inwoner/pdc/tests/test_product.py

Regression test for the issue that was fixed in https://github.com/maykinmedia/open-inwoner/pull/813

:white_check_mark: [#1809] Regression test for CTA button on product page

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/accounts/tests/test_auth.py

The new version validates BSN numbers during the mock login flow.
This will prevent issues like Taiga [#1814](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1814) by requiring users to enter a BSN that satifies pattern validation as well as the 11-check.

[#1814] Upgraded digid-eherkenning to 0.9

---

src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/components/templates/components/Dashboard/Dashboard.html
src/open_inwoner/components/templatetags/dashboard_tags.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss
src/open_inwoner/scss/components/Container/Container.scss
src/open_inwoner/scss/components/Dashboard/Dashboard.scss
src/open_inwoner/scss/components/Grid/Grid.scss
src/open_inwoner/scss/components/Spinner/Spinner.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/cases/status_inner.html
src/open_inwoner/templates/pages/cases/status_outer.html
src/open_inwoner/templates/pages/contactmoment/detail.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1793
The newly. designed Dashboard component requires restructuring of the detail page grid + has impact on Contactmoment detail page.
Also: Anchormenu references need to be removed for Case detail 
(and from Case list in other PR).
Note: unsure which variable is needed for "Verwachte uitslag" (now set to `end_date_legal`)

[#1794] Redesign case detail-page header

---

src/open_inwoner/components/templates/components/StatusIndicator/StatusIndicator.html
src/open_inwoner/templates/pages/cases/list_inner.html

Noticed that the heading was duplicated after the refactor of the case list
Also noticed that the status indicator header was always added, even if the status indicator is empty, resulting in unnecessary spacing at the top of the card

:lipstick: Fix case list styling issues

---

src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/cases.py

Fixes two problems with the recent refactor of the case list ([PR 804](https://github.com/maykinmedia/open-inwoner/pull/804/files))
- the filtering of non-visible zaken was performed in the wrong place, which slowed down page load
- the addition of info_context to upload documents needs to check for `AttributeError` to account for zaken without status

Fixed case filtering in list view and AttributeError in detail view

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/components/templates/components/Notification/Notification.html
src/open_inwoner/components/templates/components/Notification/Notifications.html
src/open_inwoner/components/templatetags/string_tags.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/scss/components/Notification/_Notification.scss
src/open_inwoner/templates/pages/cases/status_inner.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/1797

:sparkles: [#1797] Show filename(s) in success msg for document upload

---

src/open_inwoner/pdc/managers.py
src/open_inwoner/pdc/tests/test_views.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1837

:sparkles: [#1837] Category visibility for DigiD/eHerkenning

---

src/open_inwoner/configurations/admin.py
src/open_inwoner/configurations/tests/test_admin.py

Taiga [#1830](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1830)

[#1830] Prevent deletion of last website

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/accounts/choices.py
src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_action_views.py
src/open_inwoner/cms/extensions/constants.py
src/open_inwoner/conf/base.py
src/open_inwoner/configurations/choices.py
src/open_inwoner/configurations/models.py
src/open_inwoner/custom_csp/constants.py
src/open_inwoner/media/choices.py
src/open_inwoner/openklant/constants.py
src/open_inwoner/pdc/choices.py
src/open_inwoner/plans/choices.py
src/open_inwoner/search/constants.py

Taiga [#1769](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1769)

[#1769] Replace deprecated djchoices with native Django choices

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/components/templates/components/File/File.html
src/open_inwoner/components/templates/components/File/FileList.html
src/open_inwoner/components/templatetags/file_tags.py
src/open_inwoner/conf/base.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/scss/components/File/File.scss
src/open_inwoner/scss/components/Status/_Status.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/cases/status_inner.html
src/open_inwoner/utils/time.py

Taiga [#1798](https://taiga.maykinmedia.nl/project/open-inwoner/task/1798)
- added creation date to documents
- added indicator for recently added documents ("recently added" made configurable)
TODO:
- the size of the document icon on the left needs to adjust dynamically, depending on whether the "recently added" indicator is present or not (currently the size is hardwired via padding)

[#1798] Refactored document list in case detail view

---

src/open_inwoner/cms/cases/forms.py
src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/components/templates/components/Notification/Notification.html
src/open_inwoner/components/templatetags/form_tags.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/templates/pages/cases/document_form.html
src/open_inwoner/utils/forms.py

Taiga: [#1795](https://taiga.maykinmedia.nl/project/open-inwoner/task/1795)
Front-end: [PR #833](https://github.com/maykinmedia/open-inwoner/pull/833)

[#1795] Add backend support for multiple file upload

---

src/open_inwoner/accounts/tests/factories.py
src/open_inwoner/pdc/managers.py
src/open_inwoner/pdc/tests/test_views.py

Based on https://github.com/maykinmedia/open-inwoner/pull/854, so that should be merged first
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1866

:sparkles: [#1866] Enable category personalization based on KvK number

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/templates/django_registration/registration_form.html
src/open_inwoner/accounts/templates/registration/login.html
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/views/registration.py
src/open_inwoner/conf/ci.py

Based on https://github.com/maykinmedia/open-inwoner/pull/859, so that should be merged first
task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1878
Aside from adapting the necessary registration form, the following was also changed/added:
- added eHerkenning link to registration page
- made DigiD/eHerkenning links on registration page conditional based on `settings.DIGID_ENABLED` and `SiteConfiguration.eherkenning_enabled`

:sparkles: [#1878] Post-login registration form for eHerkenning

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/components/templates/components/AnchorMenu/AnchorMenu.html
src/open_inwoner/configurations/tests/test_show_actions.py
src/open_inwoner/scss/components/List/_List.scss
src/open_inwoner/scss/components/Profile/_personal-overview.scss
src/open_inwoner/scss/components/Table/Tabled.scss
src/open_inwoner/templates/pages/profile/edit.html
src/open_inwoner/templates/pages/profile/me.html

Taiga [#1706](https://taiga.maykinmedia.nl/project/open-inwoner/task/1706)

[#1706] Redesign personal info page

---

src/open_inwoner/templates/pages/cases/status_inner.html

Possibly removed during a merge?
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1881

:lipstick: [#1881] Add indicator back to document-list

---

src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/openzaak/cases.py

Prevents retrieval of Zaken if fetching with RSIN is enabled but RSIN is missing
Taiga [#1867](https://taiga.maykinmedia.nl/project/open-inwoner/task/1867)

[#1867] Prevent retrieval of zaken with missing rsin

---

src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/tests/test_cases.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1904
if the ZGW APIs reuse StatusTypen for different ZaakTypen, we end up with multiple `ZaakTypeStatusTypeConfig` that have the same `statustype_url`, which led to errors when retrieving these configs. To fix this we explicitly filter for the correct `ZaakTypeConfig` as well

:bug: [#1904] Fix Case list crashing due to reused Statustypen

---

src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/components/templates/components/Action/Actions.html
src/open_inwoner/components/templates/components/File/File.html
src/open_inwoner/conf/parts/maileditor.py
src/open_inwoner/plans/tests/test_views.py
src/open_inwoner/templates/export/profile/profile_export.html
src/open_inwoner/templates/pages/history.html
src/open_inwoner/templates/pages/plans/list.html
src/open_inwoner/templates/pages/profile/me.html
src/open_inwoner/templates/pages/profile/mydata.html

Dates should have the format `26 october 1985` consistently.
Taiga [#1899](https://taiga.maykinmedia.nl/project/open-inwoner/task/1899)

[#1899] Use NLDS-compliant date format consistently

---

src/open_inwoner/templates/master.html

in order to improve Tab order, issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1884

:wheelchair: [#1884] Make cookiebanner be the first element to load

---

src/open_inwoner/js/components/form/FileInput.js
src/open_inwoner/scss/components/Form/NonFieldError.scss
src/open_inwoner/templates/pages/cases/document_form.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1891
PR that needed improvement: https://github.com/maykinmedia/open-inwoner/pull/858 (see resolved issues)

[#1891] Remnant PR review errors selected documents

---

src/open_inwoner/accounts/tests/test_contact_views.py

It is kinda interesting how this happens on CI.
It feels like there is something funny going on in the random state/logic it uses to select the next name; somehow on CI it re-uses exactly the same in this same test.

[#1851] Fixed flakey ContactView test

---

src/open_inwoner/cms/products/tests/test_plugin_categories.py
src/open_inwoner/pdc/managers.py

https://taiga.maykinmedia.nl/project/open-inwoner/issue/1932

[#1932] Skipping zaaktype in case identificatie doesn't exist in zaaktype list

---

src/eherkenning/mock/eherkenning_urls.py
src/eherkenning/mock/views/eherkenning.py
src/eherkenning/tests/test_mock_views.py
src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_profile_views.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1915
As discussed, deleting the local session is sufficient to logout of eHerkenning

:recycle: [#1915] Use regular logout endpoint for eHerkenning logout

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/tests/test_case_detail.py

`InnerCaseDetailView.get_second_status_preview` occasionally failed due to a `TypeError` because case status types retrieved via the eSuite don't always contain a `volgnummer`.
I added a check to the function and updated the annotation of our `StatusType` api model
Taiga [#1928](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1928)

[#1928] Check missing volgnummer for second status preview

---

src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/factories.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/components/templatetags/button_tags.py
src/open_inwoner/configurations/tests/test_show_actions.py
src/open_inwoner/scss/components/Button/Button.scss
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/List/_List.scss
src/open_inwoner/scss/components/Profile/_personal-overview.scss
src/open_inwoner/scss/components/Table/Table.scss
src/open_inwoner/scss/components/Table/Tabled.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/profile/me.html

Taiga [#1895](https://taiga.maykinmedia.nl/project/open-inwoner/task/1898)

[#1898] Design profile page for businesses

---

src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail.py

Taiga [#1963](https://taiga.maykinmedia.nl/project/open-inwoner/task/1963)

[#1963] Sort documents in case detail view

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail.py

__init__ is only called once upon app start, not per pageview
https://stackoverflow.com/questions/46599145/django-class-view-init
And we also need to filter the statustypeconfig/resulttypeconfigs on the zaaktypeconfig, as the eSuite has one statustype linked to multiple zaaktypes. Otherwise we most likely are using the statustypeconfig from a different zaaktype

[#1991] StatusTypeConfig configuration not refreshing 

---

src/open_inwoner/components/templates/components/UserFeed/UserFeed.html
src/open_inwoner/scss/components/File/File.scss
src/open_inwoner/scss/components/Status/_Status.scss
src/open_inwoner/scss/components/Typography/H2.scss
src/open_inwoner/scss/components/UserFeed/UserFeed.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/templates/pages/cases/status_inner.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1951
This 'placeholder' template, showing 2 cards, is not dynamic yet! Depends on [Taiga issue #1760](https://taiga.maykinmedia.nl/project/open-inwoner/task/1760).
Design: https://www.figma.com/file/iKGhWhstaLIlFSaND2q7cE/OIP---Designs-(new)?type=design&node-id=717%3A12249&mode=dev
The Danger/Warning color is default for Actions - when back-end is done, the 2 cards can be merged into 1 with dynamic CSS classes.
➕ adding new pattern for H2's that need to have an indicator dot.

[#1951] Add userfeed frontend component

---

src/open_inwoner/components/templates/components/Pagination/Pagination.html

Has been bothering me for a while now that we show pagination with a [1] if you don't have multiple pages

[#1983] Only show pagination if there are multiple pages

---

src/eherkenning/tests/test_mock_views.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_oidc_views.py
src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/cms/cases/views/mixins.py
src/open_inwoner/kvk/branches.py
src/open_inwoner/kvk/middleware.py
src/open_inwoner/kvk/tests/test_views.py
src/open_inwoner/kvk/views.py
src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/utils/test.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1949

:sparkles: [#1949] Mijn aanvragen filtering by vestigingsnummer

---

src/open_inwoner/accounts/signals.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/cms/cases/tests/test_contactform.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openklant/services.py
src/open_inwoner/openklant/tests/data.py
src/open_inwoner/openklant/tests/test_signal.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1957

:sparkles: [#1957] Implement remaining Klant resource usage for companies

---

src/open_inwoner/js/components/form/FileInput.js

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1975
the FileInput field now keeps previously selected document after drag and dropping new files to upload

:bug: [#1975] Fix selecting of multiple documents to upload

---

src/open_inwoner/accounts/backends.py
src/open_inwoner/accounts/tests/test_backends.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1998
to avoid the regular OIDC backend triggering for logins with DigiD via OIDC, which might result in errors

:bug: [#1998] Check if path matches callback in OIDC backends

---

src/digid_eherkenning_oidc_generics/backends.py
src/open_inwoner/accounts/tests/test_oidc_views.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1931
to allow the ID claim name to differ from the fieldname on our model

:recycle: [#1999] Use fixed unique ID fieldname for OIDC

---

src/open_inwoner/js/components/form/FileInput.js

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1975

🐛 [#1975] Keep previous selection when selecting new files to upload

---

src/open_inwoner/openzaak/notifications.py
src/open_inwoner/openzaak/tests/test_notification_data.py
src/open_inwoner/openzaak/tests/test_notification_zaak_infoobject.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2002

:sparkles: [#2002] Implement Zaken notifications for companies

---

docker/openklant/fixtures/db.json
src/open_inwoner/accounts/signals.py
src/open_inwoner/accounts/views/contactmoments.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openklant/services.py
src/open_inwoner/openklant/tests/data.py
src/open_inwoner/openklant/tests/test_views.py
src/open_inwoner/openklant/views/contactform.py
src/open_inwoner/openklant/wrap.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1950

:sparkles: [#1950] Filter by vestigingsnummer in Mijn Vragen

---

src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/js/components/cases/status_accordion.js
src/open_inwoner/js/components/form/FileInput.js
src/open_inwoner/scss/components/Cases/CaseDetail.scss

Issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1978 
1. upload button must be invisible at first, + 'geselecteerde bestanden' must be invisible.
2. upload button becomes visible when file(s) are selected, + 'geselecteerde bestanden' becomes visible.
3. visible upload button becomes disabled if data-max-file-size is exceeded, but becomes enabled again when those selected files are removed with trash button.

[#1978] Make uploadbutton and title show only when files are selected

---

package-lock.json
package.json

Issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1958
Note, besides 'Material **ICONS**' there is also something called 'Material **SYMBOLS**' which is being developed by Google and seems to have been incorporated into Figma - some icons look slightly different, bit it also uses a very different technology (instead of regular/bold thickness, it uses a GRADUAL way to increase linethickness for these icons) so no need to change into that one yet.
https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=key  
versus 
https://fonts.google.com/icons?icon.set=Material+Symbols&icon.query=key

:lipstick: [#1958] Update material icons

---

src/open_inwoner/ssd/client.py
src/open_inwoner/ssd/tests/test_client.py
src/open_inwoner/ssd/xml.py

Taiga [#1956](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1956)

[#1956] Return None from SSD client on RequestsException

---

src/open_inwoner/conf/base.py
src/open_inwoner/pdc/tests/test_product.py
src/open_inwoner/pdc/tests/test_product_form.py
src/open_inwoner/pdc/views.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1944

🔒 [#1944] Set default Referrer-Policy to same-origin 

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependencies.yml
.gitmodules
Dockerfile
INSTALL.rst
package-lock.json
package.json
src/open_inwoner/accounts/templates/accounts/inbox.html
src/open_inwoner/cms/banner/tests/test_plugin_banner.py
src/open_inwoner/scss/components/Dashboard/Dashboard.scss
src/open_inwoner/scss/components/Header/AnchorMenu.scss
src/open_inwoner/scss/components/Tags/TagList.scss
src/open_inwoner/scss/components/Typography/H1.scss
src/open_inwoner/scss/components/Typography/H2.scss
src/open_inwoner/scss/components/Typography/H3.scss
src/open_inwoner/scss/screen.scss
src/open_inwoner/templates/cms/banner/banner_text_plugin.html
src/open_inwoner/templates/cms/fullwidth.html
src/open_inwoner/templates/master.html
src/open_inwoner/templates/pages/cases/list_inner.html
src/open_inwoner/templates/pages/cases/status_inner.html
src/open_inwoner/templates/pages/category/detail.html
src/open_inwoner/templates/pages/home.html
src/open_inwoner/templates/pages/product/detail.html
src/open_inwoner/templates/pages/user-home.html

- add our [designtokens-package submodule](https://github.com/maykinmedia/open-inwoner-design-tokens)
- add Utrecht CSS NPM package + Utrecht Components NPM package
- add actions for submodules to CI yml's
- add Utrecht classes in some heading templates
- let Utrecht design variable **Keys** point to OIP variable **Values**
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1910

:sparkles: [#1910] Add first NL-DesignSystem components

---

src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/kvk/client.py
src/open_inwoner/kvk/tests/mocks.py
src/open_inwoner/kvk/tests/test_api.py
src/open_inwoner/kvk/tests/test_views.py
src/open_inwoner/kvk/views.py

Make sure that the main company branch ("hoofdvestiging") comes before any subsidiary ("nevenvestiging")
Taiga: [#2004](https://taiga.maykinmedia.nl/project/open-inwoner/task/2004)

[#2004] Fix order of company branches

---

.gitmodules

issue: also connected to #909  maybe connecting to a tag in future

[#2032] Make submodule update from main branch

---

src/open_inwoner/accounts/admin.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/1885
In the pentest you could upload here, but this is user content so no need to create/edit it through the admin.
Fields:

[#1885] Changed document admin to be readonly

---

src/eherkenning/tests/test_mock_views.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_oidc_views.py
src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/cms/cases/views/mixins.py
src/open_inwoner/kvk/branches.py
src/open_inwoner/kvk/forms.py
src/open_inwoner/kvk/middleware.py
src/open_inwoner/kvk/tests/test_views.py
src/open_inwoner/kvk/views.py
src/open_inwoner/openklant/wrap.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/pdc/managers.py
src/open_inwoner/templates/pages/kvk/branches.html

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2027
previously, in case the user did not select a branch, the KVK_BRANCH_NUMBER would be set to the KVK, which meant that everywhere this sessionvariable was used, it had to be compared to the KVK number to see if it was an actual branch number or if it was set just to skip the branch selection screen

:recycle: [#2027] Only set KVK branch sessionvar if branch is selected

---

src/open_inwoner/cms/cases/views/status.py

Taiga [#2007](https://taiga.maykinmedia.nl/project/open-inwoner/task/2007)

[#2007] Disable upload message if there are recently uploaded documents

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail.py

Regression test for Taiga issue [#2037](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2037) ([PR 981](https://github.com/maykinmedia/open-inwoner/pull/981/files))
Taiga: [2045](https://taiga.maykinmedia.nl/project/open-inwoner/task/2045)

[#2045] Add regression test for e-suite missing statuses

---

src/open_inwoner/cms/cases/tests/test_contactform.py
src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/cms/products/tests/test_plugin_categories.py
src/open_inwoner/openklant/tests/data.py
src/open_inwoner/openklant/tests/test_signal.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_case_request.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/openzaak/tests/test_cases_cache.py
src/open_inwoner/openzaak/tests/test_documents.py
src/open_inwoner/openzaak/tests/test_zgw_imports.py
src/open_inwoner/openzaak/tests/test_zgw_imports_iotypes.py
src/open_inwoner/search/tests/test_views.py

Let's use `generate_oas_component_cached()` in all the relevant setUp()'s and see what it does for test runtime.
I also refactored/restored some ZGW tests that earlier sacrificed test-isolation for performance, by using the setupTestData class-method, but this is no longer needed. This is slightly slower because the normal factories run for every tests but it is safer and more correct.

Applied generate_oas_component_cached() where applicable

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail.py

Taiga: [#2049](https://taiga.maykinmedia.nl/project/open-inwoner/task/2049)
Regression test for cases where eSuite associates multiple `statustypen` with the same `zaaktype`. Taiga issue [1971](https://taiga.maykinmedia.nl/project/open-inwoner/task/1971)

[#2049] Add regression test for eSuite multiple end statustypes

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

task: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2066
pip-tools was stuck on a version that doesn't work properly for python3.11

:arrow_up: [#2066] Upgrade psycopg2 to 2.9.9 and pip-tools to 7.3.0

---

src/open_inwoner/openzaak/tests/test_case_detail.py

Taiga: [#2047](https://taiga.maykinmedia.nl/project/open-inwoner/task/2047)
- Added test to ensure case documents are ordered by date
- Changed mocks to ensure document ordering works with time + offset (e.g. `registratiedatum="2022-12-12T00:00:00+01:00"`)

[#2047] Regression test eSuite case document ordering 

---

src/open_inwoner/components/templates/components/Card/CardContainer.html
src/open_inwoner/components/templates/components/Card/RenderCard.html
src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/components/templatetags/card_tags.py
src/open_inwoner/js/components/form/FileInput.js
src/open_inwoner/scss/components/Form/FileInput.scss
src/open_inwoner/templates/pages/cases/document_form.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/1982 
Plus: also fixed the issue where the delete button became non-functional when more than 1 faulty file is selected.

[#1982] Add file-type error validation for document-upload

---

requirements/dev.in
requirements/dev.txt
src/open_inwoner/conf/dev.py
src/open_inwoner/urls.py

I found silk quite handy when trying to locate performance bottlenecks

🔧 Setup silk profiling

---

src/open_inwoner/conf/base.py
src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/openzaak/tests/test_cases_cache.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2089

:zap: [#2089] Use multithreading for Mijn Aanvragen list

---

src/open_inwoner/scss/components/Header/Header.scss
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss
src/open_inwoner/scss/views/App.scss

Issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2115
Also: a small fix for the dyslexia drop-down menu

:lipstick: [#2115] Forced default bold for headings 

---

src/open_inwoner/components/templates/components/Card/CategoryCard.html
src/open_inwoner/components/templates/components/Card/DescriptionCard.html
src/open_inwoner/components/templates/components/Card/LocationCard.html
src/open_inwoner/components/templates/components/Card/ProductCard.html
src/open_inwoner/components/templates/components/Card/RenderCard.html
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/Profile/_personal-overview.scss
src/open_inwoner/templates/cms/collaborate/active_plans_plugin.html
src/open_inwoner/templates/pages/cases/list_inner.html
src/open_inwoner/templates/pages/profile/me.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2111 
1. aligning 'Mijn aanvragen' icons optically to new line-height (even if they are correctly aligned, you might see an "optical illusion" where triangular shaped icons look different from the rest)
2. adjusting all card-headings + give them meaningful classnames

:lipstick: [#2111] Fix case-card icons and adjust card headings

---

src/open_inwoner/conf/parts/case_status_notification.html
src/open_inwoner/conf/parts/case_status_notification_action_required.html
src/open_inwoner/static/mailcss/email.css
src/open_inwoner/templates/mail/_base.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2118

[#2118] Add links in email template, improve padding

---

src/open_inwoner/kvk/tests/test_signals.py
src/open_inwoner/utils/tests/playwright.py

these tests seem to fail since https://github.com/maykinmedia/open-inwoner/pull/963 was merged, possibly related to the App.scss font-face changes

💚 Add font files in playwright tests

---

src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_password_reset_view.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/tests/test_case_detail.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1916

:white_check_mark: [#1916] Fix flakey password reset throttling test

---

src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/openzaak/clients.py
src/open_inwoner/openzaak/management/commands/zgw_dev_status.py
src/open_inwoner/openzaak/utils.py
src/open_inwoner/pdc/managers.py
src/open_inwoner/search/views.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2088

:sparkles: [#2088] Implement Zaken search for eHerkenning users

---

src/open_inwoner/ssd/templates/maandspecificatie.html
src/open_inwoner/ssd/tests/test_views.py
src/open_inwoner/templates/pages/ssd/monthly_reports_list.html

Taiga: [#1808](https://taiga.maykinmedia.nl/project/open-inwoner/issue/1808)
- set empty title in PDF templates to prevent duplication of report name in tab
- use long month name in case no reports are found

[#1808] Use long month names consistently in ssd templates

---

src/open_inwoner/scss/components/Typography/wysiwyg.scss
src/open_inwoner/templates/master.html

issue https://taiga.maykinmedia.nl/project/open-inwoner/task/2117
This is for situations where we have CKeditor elements/tags that do not have project style-classes.
I moved this into a higher priority because I see Enschede is experimenting with the footer: https://mijn-acceptatie.enschede.nl/accounts/login/ (scroll down to see footer)

:lipstick: [#2117] Tag styles for wysiwyg in footer

---

src/open_inwoner/accounts/backends.py
src/open_inwoner/accounts/tests/test_oidc_views.py
src/open_inwoner/conf/fixtures/django-admin-index.json
src/open_inwoner/configurations/tests/test_oidc.py
src/open_inwoner/scss/admin/_app_overrides.scss
src/open_inwoner/templates/admin/login.html
src/open_inwoner/templates/maykin_2fa/login.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2101
Fixes two issues:
- If an OIDC user logs in for the first time, they are now actually authenticated (previously they had to log in twice)
- If OIDC is enabled for admins, the `is_staff` attribute is set for those users (according to the OIDC config) and they are redirected to the admin interface

:wrench: [#2101] Add OIDC admin config to admin index fixture

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1768
to make use of configurable client timeout

:arrow_up: Upgrade django-open-forms-client to 0.3.0

---

src/open_inwoner/pdc/managers.py
src/open_inwoner/pdc/tests/test_views.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2143

🐛 [#2143] Show all categories to staff users

---

.watchmanconfig
requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/conf/base.py

and upgrade Pillow and django to clear dependabot alerts

:heavy_minus_sign: Remove unused dependencies

---

src/open_inwoner/kvk/middleware.py
src/open_inwoner/kvk/tests/test_middleware.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2146

🐛 [#2146] Avoid KvK branch select redirects for media files

---

requirements/ci.txt
requirements/dev.txt
requirements/test-tools.in
src/open_inwoner/accounts/gateways.py
src/open_inwoner/components/templatetags/form_tags.py
src/open_inwoner/media/admin/__init__.py

The flake8 dependency was ancient and needed to update so we can use autoflake
With autoflake you can automatically fix some flake8 issues, so it works similar to black and isort.
I use this mostly for unused imports, because I always forget:
````
autoflake --in-place --remove-all-unused-imports
````
(also fixed some issues from new tooling)

Updated flake8 dependency, added autoflake

---

src/open_inwoner/accounts/templates/accounts/registration_necessary.html
src/open_inwoner/scss/components/Form/Checkbox.scss
src/open_inwoner/templates/pages/profile/notifications.html

Issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2137 
To explicitly show required-actions notifications cannot be turned off (on http://localhost:8000/mijn-profiel/notificaties/).
➕ also making the pseudo checkbox accessible (⚠️ ordinary **disabled** inputs are **_not_** detected by screenreaders and are not read + cannot be focussed, so making a _visual_ fake checkbox here that actually gets detected).
A disabled input that cannot be enabled by the user in any way is a violation of accessibility.

[#2137] Show disabled pseudo-checkbox for actions

---

src/open_inwoner/accounts/signals.py
src/open_inwoner/haalcentraal/signals.py
src/open_inwoner/haalcentraal/tests/test_signal.py
src/open_inwoner/haalcentraal/utils.py

This was kind of gnarly:
1. We can't use `pre_save` signal because we need a saved user
2. Calling save() from either a `pre_save` or `post_save` handler creates a signal loop
Solution: use `post_save` so we have a saved user, and break the loop.
Downside is this will trigger any other `post_save` handler multiple times, which is a vote to centralize signal based user update stuff. Most of it is currently `user_logged_in` so not an issue.
Note this PR targets the open Django 4.x branch #1024

Fixed user save-signal issue with Haalcentraal BRP retrieval logging

---

src/open_inwoner/openzaak/notifications.py
src/open_inwoner/openzaak/tests/test_notification_utils.py
src/open_inwoner/openzaak/tests/test_notification_zaak_status.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2166

:bug: [#2166] Make status argument for send_case_update_email optional

---

src/open_inwoner/js/components/form/ChoiceListSingle.js
src/open_inwoner/js/components/form/index.js
src/open_inwoner/kvk/tests/test_views.py
src/open_inwoner/scss/components/Form/ChoiceList.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/kvk/branches.html

issue https://taiga.maykinmedia.nl/project/open-inwoner/task/2026 
design: https://www.figma.com/file/iKGhWhstaLIlFSaND2q7cE/OIP---Designs-(new)?type=design&node-id=481-4737&mode=design&t=Rf5MsQFFdwpCVUqV-0

[#2026] KVK branch selection

---

src/open_inwoner/conf/parts/maileditor.py

Taiga detail issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2170
First discussion of issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2134

[#2170] Fix profile-notifications for mail-templates

---

src/open_inwoner/accounts/views/contactmoments.py
src/open_inwoner/js/components/form/DisableContactFormButton.js
src/open_inwoner/js/components/form/index.js
src/open_inwoner/js/components/index.js
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/Cases/CaseDetail.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/templates/pages/cases/contact_form.html
src/open_inwoner/templates/pages/contactmoment/list.html

Taiga: [#2099](https://taiga.maykinmedia.nl/project/open-inwoner/task/2099)
Related: PR https://github.com/maykinmedia/open-inwoner/pull/1059

[#2099] Re-design mijn vragen

---

src/open_inwoner/conf/parts/case_document_notification.html
src/open_inwoner/conf/parts/case_status_notification.html
src/open_inwoner/conf/parts/case_status_notification_action_required.html
src/open_inwoner/static/mailcss/email.css
src/open_inwoner/templates/mail/_base.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2175
- check rounded corners for Gmail on Android
This fix does not use fallbacks, instead the issue was that the Table with rounded area got a white background, which cut through the rounded corners and made it seem not-rounded.
PS: the border-radiuses in the design are only 3px so not dramatically visible.

[#2175] Fix rounded corners for mail-templates

---

src/open_inwoner/accounts/views/profile.py
src/open_inwoner/laposta/client.py
src/open_inwoner/laposta/forms.py
src/open_inwoner/laposta/tests/test_forms.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2192
~~Based on #1082, so that should be merged first~~

✨ [#2192] Display newsletter form errors to user

---

src/open_inwoner/accounts/apps.py

Error handling when django-admin-index could not be loaded was missing exception info and return.

Fixed autoload of django-admin-index

---

src/open_inwoner/components/templates/components/Header/WarningHeader.html
src/open_inwoner/scss/components/WarningHeader/WarningHeader.scss

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/1811

:lipstick: [#1811] Fix spacing warning-header text

---

src/open_inwoner/accounts/views/contactmoments.py
src/open_inwoner/openklant/tests/test_views.py

Taiga: [#2234](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2234)

[#2234] Fix subject for questions without e-suite code mapping

---

src/open_inwoner/js/components/card/ToggleHide.js
src/open_inwoner/js/components/index.js
src/open_inwoner/templates/pages/cases/status_inner.html
src/open_inwoner/templates/pages/questions/question.html
src/open_inwoner/templates/pages/questions/questions.html

Toggle hide/show was broken because the toggle was attached to the wrong node in the DOM
Taiga: [#2235](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2235)
Feature PR for mijn-aanvragen/vragen link: [#2098](https://github.com/maykinmedia/open-inwoner/pull/1059)

[#2235] Fix toggle-hide for case-related questions

---

src/open_inwoner/cms/plugins/cms_plugins/userfeed.py
src/open_inwoner/openzaak/clients.py
src/open_inwoner/userfeed/feed.py
src/open_inwoner/userfeed/hooks/external_task.py
src/open_inwoner/userfeed/tests/test_external_tasks.py
src/open_inwoner/userfeed/tests/test_feed.py

issues: 
- https://taiga.maykinmedia.nl/project/open-inwoner/issue/2280
- https://taiga.maykinmedia.nl/project/open-inwoner/issue/2269

:bug: [#2280/2269] Properly catch errors when fetching openstaande taken

---

src/open_inwoner/accounts/views/contactmoments.py
src/open_inwoner/openklant/tests/test_views.py

If no mapping exists for e-suite for a particular e-suite subject code (or if duplicate codes exist), we use the first OIP configured subject as fallback
Taiga: [#2277](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2277)

[#2277] Use first OIP subject for questions as fallback

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/notifications.py
src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/openzaak/tests/test_notification_data.py
src/open_inwoner/openzaak/utils.py
src/open_inwoner/userfeed/hooks/case_status.py
src/open_inwoner/utils/translate.py

Taiga: [#2217](https://taiga.maykinmedia.nl/project/open-inwoner/task/2217)

[#2217] Use 'statustekst' as default case status label

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/laposta/api_models.py
src/open_inwoner/qmatic/client.py
src/open_inwoner/utils/api.py

task: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2279
~~based on #1103, so that should be merged first~~

⬆️ [#2279] Upgrade pydantic to 2.6.4

---

src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/components/templates/components/List/ListItem.html
src/open_inwoner/scss/components/Card/CardGrid.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/List/_ListItem.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/templates/pages/cases/list_inner.html
src/open_inwoner/templates/pages/profile/appointments.html

task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2241
~~Based on #1103, so that should be merged first~~

:lipstick: [#2241] Make appointment list conform to design

---

src/open_inwoner/accounts/tests/test_contact_views.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/cms/tests/cms_tools.py
src/open_inwoner/cms/tests/test_page_display.py
src/open_inwoner/cms/utils/page_display.py

Also added tests for page_display helpers
The problem was `Page.application_namespace` is not always the clean 'app_name' but gets postfixed with `-app-config` if the app-hook has an app-config. I fixed it by relying on the other field but it needs a little processing.

[#2170] Fixed issue with profile_page_is_published() & get_active_app_names() CMS helpers

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail.py

Taiga: [#2288](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2288)

[#2288] Handle None questions in case detail view

---

src/open_inwoner/accounts/templates/accounts/registration_necessary.html
src/open_inwoner/components/templates/components/Form/Checkbox.html
src/open_inwoner/js/components/form/ChoiceListMultiple.js
src/open_inwoner/js/components/form/index.js
src/open_inwoner/js/components/siteimprove/tracking.js
src/open_inwoner/scss/components/Filter/Filter.scss
src/open_inwoner/scss/components/Form/Checkbox.scss
src/open_inwoner/scss/components/Form/ChoiceList.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Form/Radio.scss
src/open_inwoner/templates/pages/kvk/branches.html
src/open_inwoner/templates/pages/profile/edit.html
src/open_inwoner/templates/pages/profile/notifications.html

Design: https://www.figma.com/file/iKGhWhstaLIlFSaND2q7cE/OIP---Designs-(new)?type=design&node-id=2217%3A9149&mode=design&t=ObhqwB8PWC3lvpzO-1
Note: instead of the Accent color, we decided to use the secondary color for all radio/checkbox inputs.
userstory : https://taiga.maykinmedia.nl/project/open-inwoner/us/2210
new issue number: https://taiga.maykinmedia.nl/project/open-inwoner/task/2245

[#2245] Registration notifications redesign

---

src/open_inwoner/conf/parts/email_verification.html
src/open_inwoner/conf/parts/maileditor.py

Task: https://taiga.maykinmedia.nl/project/open-inwoner/task/2292

[#2292] Style 'email_verification' mail-template

---

src/open_inwoner/scss/components/Card/CardGrid.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/Contactmomenten/Contactmomenten.scss
src/open_inwoner/scss/components/Pagination/Pagination.scss
src/open_inwoner/scss/components/UserFeed/UserFeed.scss

This PR solves wrong section styles and some other faulty gaps/margins/paddings here and there.
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2194 
the main issue is a bit of a ['blame' because some styles were put inside 'contactmomenten' that did not belong there](https://github.com/maykinmedia/open-inwoner/pull/1045/files#diff-715ac754308c4741d154fa5bad16a14a6a78c544ac23aaff2571b33a8cd0e2a2R120)  + all Section tags in the entire project were styled wrong because of the CSS that was targeting all Section Tags instead of a `.[componentname]-section` class (we need to target components instead of everything everywhere all at once 🙂)
inside scope of this issue:
outside scope of this issue so did is as an extra

:lipstick: [#2194] Correct use of Sections and other gaps

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

this was previously removed, but it was still in use

:heavy_plus_sign: Re-add beautifulsoup4 to deps

---

src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/utils/glom.py
src/open_inwoner/utils/tests/test_glom.py

https://taiga.maykinmedia.nl/project/open-inwoner/task/2259

[#2259] Show case result in list view

---

src/open_inwoner/haalcentraal/api.py
src/open_inwoner/haalcentraal/tests/test_client.py

Taiga: [#2274](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2274)

[#2274] Pass data in Haalcenntraal POST as JSON

---

src/open_inwoner/components/templates/components/File/File.html
src/open_inwoner/components/templates/components/File/FileTable.html
src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/js/components/form/FileInput.js
src/open_inwoner/scss/components/Cases/CaseDetail.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/scss/components/File/File.scss
src/open_inwoner/scss/components/File/FileList.scss
src/open_inwoner/scss/components/Form/FileInput.scss
src/open_inwoner/scss/components/Grid/Grid.scss
src/open_inwoner/scss/components/Typography/H2.scss
src/open_inwoner/scss/components/UserFeed/UserFeed.scss
src/open_inwoner/templates/cms/plugins/userfeed/userfeed.html
src/open_inwoner/templates/pages/cases/status_inner.html
src/open_inwoner/templates/pages/cases/status_outer.html
src/open_inwoner/templates/pages/cases/statuses.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2272
The nature of 'shrinking' a breaking text [where the wrap-width is unknown](https://stackoverflow.com/questions/37406353/make-container-shrink-to-fit-child-elements-as-they-wrap) turned out quite difficult; therefor I am using a  rather unique grid in order to make the indicator appear as close to the breaking text as possible with media-queries.
In this PR I am also fixing the ellipsis for long file-names 
➕ minor improvements of the case-detail page.
To test dot for file-list, increase default value of `DOCUMENT_RECENT_DAYS = config("DOCUMENT_RECENT_DAYS", default=1)`

:lipstick: [#2272] Position indicator dot headings

---

src/open_inwoner/configurations/tests/bootstrap/test_setup_auth_config.py

Python-saml dependency got updated so patch() had to be retargeted

Fixed issue with setup configuration tests

---

src/open_inwoner/accounts/templates/registration/login.html
src/open_inwoner/js/components/form/LoginForm.js
src/open_inwoner/js/components/tab-panels/index.js
src/open_inwoner/scss/components/TabPanel/TabPanel.scss

issue here: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2328 
refactor from feedback on #992

[#2328] Refactor tabpanels on login page

---

src/open_inwoner/components/templates/components/File/File.html
src/open_inwoner/scss/components/Cases/CaseDetail.scss

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2377
Unnecessary aria-label that results into screenreader reading the same thing twice.
Plus corrected small spacing bug.

:wheelchair: [#2377] Remove aria-label from aside

---

src/open_inwoner/openklant/views/contactform.py

Taiga: [#2240](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2240)
As far as I can see, this was the only place that didn't either check for open redirects or redirect to some hardcoded url, an object's canonical url etc. (it was also the only source reported by GitHub).

[#2240] Avoid open redirects through contactform

---

src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/List/_List.scss
src/open_inwoner/scss/components/Profile/_personal-overview.scss
src/open_inwoner/templates/pages/cases/list_inner.html
src/open_inwoner/templates/pages/contactmoment/list.html
src/open_inwoner/templates/pages/profile/appointments.html
src/open_inwoner/templates/pages/profile/me.html
src/open_inwoner/templates/pages/questions/question.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2346 
Turns out there were faulty Spans around LI's inside UL's in some Cards pages + also wrong use of paragraph tags in case of empty list-items. Also: Headings should not be a direct child inside UL's.

:wheelchair: [#2346] Remove spans, correct list-items

---

src/open_inwoner/components/templates/components/Button/Button.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2373
A small change with big effects.
aria-labels only work on interactive elements and need to at least 'contain' keywords that are inside the visible or invisible text of the component.
Side note: title attributes are not meant for accessibility, and should **actually** contain different, more meaningful text than the readable text of an interactive element. But this has not been addressed as an issue anywhere in the report - so we're only changing the aria-label here, as per request.
TL;DR: I changed the order of `{% firstof title text %}`

:wheelchair: [#2373] Make aria-labels same as (hidden) texts

---

src/open_inwoner/accounts/views/auth.py

The `DIGID` setting was removed and `login_url` wasn't actually set on this dictionary either

:bug: [#2383] Fix 500 error after cancelling DigiD via SAML login

---

src/open_inwoner/accounts/views/profile.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2338

[#2338] Add newsletters to sidebar navigation

---

src/open_inwoner/cms/plugins/tests/test_userfeed.py
src/open_inwoner/scss/components/UserFeed/UserFeed.scss
src/open_inwoner/templates/cms/plugins/userfeed/userfeed.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2064 
based on design: https://www.figma.com/file/iKGhWhstaLIlFSaND2q7cE/OIP---Designs-(new)?type=design&node-id=1460%3A5026&mode=dev
Fixing heading(=description) styling + improved the pseudo-element spacing a bit ;
not yet adding the arrow link, will be new issue if actually needed in future.
Note: I have also changed the order and HTML semantics, as this relates to this issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2352

:lipstick: [#2064] Fix userfeed styling

---

src/open_inwoner/openklant/tests/test_contactform.py
src/open_inwoner/openklant/views/contactform.py

Taiga: [#2436](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2436)

[#2436] Fix optional 'medewerkerIdentificatie' in contactmoment POST

---

src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/utils/middleware.py

A redirect cycle occurs for DigiD login when email verification is required
Taiga: [#2404](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2404)

[#2404] Avoid redirect cycle for DigiD login with email required

---

src/open_inwoner/accounts/templates/registration/login.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2381 
Branched off from #1189

:bug: [#2381] Make zakelijk tab hidden when eHerkenning is off

---

.gitignore
docker-compose.yml
docs/install/docker-compose.rst

The PR:
- adds an init volume to docker-compose so we can initialize containers with SQL dumps
- changes the port for Elasticsearch to `9201` so the Docker container can run alongside the system installation of ES without blocking the default port

Add init volume to docker-compose

---

src/open_inwoner/utils/api.py
src/open_inwoner/utils/tests/test_api_utils.py

Support for encoding IPv6 addresses was missing from the `JSONEncoderMixin` used for creating subscriptions
Taiga: [#2454](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2454)

[#2454] Add IPv6Address to JSONEncoderMixin

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependencies.yml
.gitmodules
Dockerfile
package-lock.json
package.json
src/open_inwoner/scss/components/Typography/H1.scss
src/open_inwoner/scss/components/Typography/H2.scss
src/open_inwoner/scss/components/Typography/H3.scss
src/open_inwoner/scss/components/Typography/H4.scss
src/open_inwoner/scss/components/Typography/P.scss
src/open_inwoner/scss/screen.scss
src/open_inwoner/scss/views/App.scss
src/open_inwoner/templates/pages/product/detail.html
src/open_inwoner/utils/ckeditor.py

Can only be properly reviewed when updating NPM installs and do rebuild
issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2420 
This PR removes the submodule and adds the new NPM package (specific version) so this will be built upon in the next PR's that can all be pointing to new versions of the npm package.
This PR in particular points to version 0.0.3-alpha.0 from this PR in our NLDS package:
https://github.com/maykinmedia/open-inwoner-design-tokens/pull/7
NB: this means that for these kinds of elements the single source of truth is no longer inside OIP, but ends up as a final value in the NLDS package (!). So: we are using the 'utrecht' classes which means we will not need to make our own CSS unless we need to add our own.
Explanation about NLDS architecture: …

[#2420] Set h1-h4 as NLDS in product-pages and add NPM package

---

src/open_inwoner/utils/geocode.py

Taiga: [#2466](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2466)
API docs: https://www.pdok.nl/restful-api/-/article/pdok-locatieserver-1#operation/free

[#2466] Update query parameter for PDOK API

---

src/open_inwoner/kvk/forms.py
src/open_inwoner/kvk/views.py

- Save company_branches on form instance instead of retrieving it through get_context_data to avoid multiple IO calls
- Move custom validation of branch number out of the POST of the form view and into the form itself
Taiga: [#2460](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2460)

[#2460] Refactor KVK branch view

---

src/open_inwoner/js/components/tab-panels/index.js

bug
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2508

[#2508] add ActiveTab login conditional

---

src/open_inwoner/accounts/apps.py
src/open_inwoner/conf/fixtures/django-admin-index.json
src/open_inwoner/conf/tests/test_fixtures.py

I think the mechanism wasn't broken, it just errored on bad data (there was a content-type in there that was removed).
Note it listens to the post-migrate signal (eg: not application startup). If we runt this on application start it would run for every test and management command as well (and it deletes and re-creates all the records)
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/us/2482

[#2507] Fixed and added test for 'django-admin-index' fixture

---

src/open_inwoner/mail/context.py
src/open_inwoner/mail/tests/test_context.py
src/open_inwoner/mail/tests/test_service.py

Taiga: [#2477](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2477)

[#2477] Add site name to dynamic mail context

---

src/open_inwoner/celery.py
src/open_inwoner/openzaak/tasks.py
src/open_inwoner/openzaak/tests/test_zgw_imports_task.py
src/open_inwoner/utils/admin.py

The test specific to celery-once has to be removed after converting the zgw import task to a regular celery task

Remove celery-once test

---

src/open_inwoner/templates/pages/product/form.html

BUG: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2521
quickfix for making the embedded form take open-forms's utrecht values,
instead of the utrecht values that are empty in our own NPM node-modules.

[#2521] Fix Open-Formulieren embedded form styling

---

src/open_inwoner/accounts/views/contactmoments.py
src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/cms/cases/views/mixins.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/configurations/bootstrap/zgw.py
src/open_inwoner/openzaak/cases.py
src/open_inwoner/openzaak/clients.py
src/open_inwoner/openzaak/documents.py
src/open_inwoner/openzaak/formapi.py
src/open_inwoner/openzaak/management/commands/zgw_dev_status.py
src/open_inwoner/openzaak/notifications.py
src/open_inwoner/openzaak/tests/test_case_request.py
src/open_inwoner/openzaak/tests/test_documents.py
src/open_inwoner/openzaak/zgw_imports.py
src/open_inwoner/pdc/managers.py
src/open_inwoner/search/views.py
src/open_inwoner/userfeed/hooks/external_task.py

The generic ZGW client factory has the drawback of both typing ambiguity (generic `APIClient` versus concrete `ZakenClient`), but also makes it harder to do code analysis for the purposes of migrating to a multi-ZGW-backend approach. This refactor will address both concerns.
[Taiga #2513](https://taiga.maykinmedia.nl/project/open-inwoner/us/2485)

[#2513] Refactor generic ZGW client factories to concrete equivalents

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/conf/base.py
src/open_inwoner/configurations/emails.py
src/open_inwoner/configurations/tests/test_emails.py

Reverting the previous change in [https://github.com/maykinmedia/open-inwoner/pull/1090](https://github.com/maykinmedia/open-inwoner/pull/1090)

Replace django-mailer with django-yubin

---

src/open_inwoner/accounts/views/contactmoments.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/configurations/bootstrap/kic.py
src/open_inwoner/openklant/clients.py
src/open_inwoner/openklant/services.py
src/open_inwoner/openklant/views/contactform.py
src/open_inwoner/openklant/wrap.py

The generic client factory has the drawback of both typing ambiguity (generic APIClient versus concrete KlantenClient) and poor static code analysis. This refactor will address both concerns. 
This also achieves consistency with #1226.

[#2514] Refactor generic openklant client factories to concrete equivalents

---

src/open_inwoner/utils/decorators.py
src/open_inwoner/utils/tests/test_utils.py

Taiga issue [#2524](https://taiga.maykinmedia.nl/project/open-inwoner/task/2524).
This will be followed by a PR to actually use this in the ZGW clients (and will probably also remove a few tests that were really just testing the underlying caching logic, which I've included here in a more isolated form by testing the cache behavior directly).

Add support for resolving instance attributes in the cache decorator

---

src/open_inwoner/openzaak/clients.py
src/open_inwoner/openzaak/tests/test_cases_cache.py

Taiga [#2516](https://taiga.maykinmedia.nl/project/open-inwoner/task/2516).

[#2416] Scope ZGW clients cache keys by the underlying service endpoint

---

src/open_inwoner/components/templates/components/Header/Header.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2370
de tekstuele inhoud van de Alt/Aria/Title tekstalternatieven is een taak voor redacteuren maar de hardcoded 'homepage' tekst in het Header logo moet worden verwijderd zodat het tekstalternatief volledig door de redacteur kan worden bepaald.
En: het tekstalternatief moet ook eigenlijk **starten** met de labeltekst, dus dan zou Homepage pas op het eind gezet mogen worden, maar het kan hier beter verwijderd worden,
(i.p.v. Homepage wil men bijvoorbeeld misschien "inlogpagina" gebruiken).

:wheelchair: [#2370] Enable equal text-alternative for Header and Footer logo

---

src/open_inwoner/scss/components/TabPanel/TabPanel.scss
src/open_inwoner/templates/pages/ssd/monthly_reports_list.html
src/open_inwoner/templates/pages/ssd/yearly_reports_list.html

quick-fix, because in future 'Mijn uitkeringen' will have a bigger design update, just like the login-page, and it needs to not respond to the URL-dependent javascript.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/us/2392

:bug: [#2544] Added quickfix for non-URL dependent tab panels

---

src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/scss/components/Form/FileInput.scss
src/open_inwoner/scss/views/App.scss

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2369
Will look a bit different in various browsers:

♿ [#2369] Add focus-style for custom file-input

---

src/open_inwoner/components/templates/components/Card/CategoryCard.html
src/open_inwoner/components/templates/components/Card/RenderCard.html
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/templates/pages/profile/me.html

issue: if there is no content, then there should not be any headings.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2345 
Cards that only have an image and no text content at all, should use a paragraph that may visually look like a Heading.
A real Heading is an HTML tag that should summarize/pin-point the section below it, but in case of an image it does not make sense in accessibility/meaningfulness.
Also screen-readers will read out headings as a list with hierarchy, so there better be something meaningful there.
Note : it is **outside of the scope** of this issue but some of the other cards are incorrect as well - in case a card has only a title, it's again not really a heading. Example: the sub-category card here: …

:wheelchair: [#2345] A11y replace disallowed heading tags in Cards

---

src/open_inwoner/scss/components/Card/CardGrid.scss
src/open_inwoner/scss/components/Cases/Cases.scss
src/open_inwoner/templates/pages/cases/list_inner.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2352
Meaningful sequence for accessibility: any text belonging to a heading must be below the heading
Also corrected faulty build of this Card: the entire card needs to be an anchor, including the spacing/padding.
Which means an extra complication when there is an element that needs to be independent from the other padding (the colored status indicator headers), therefore setting padding to each element inside the card body, which also influences the Grid.

♿ [#2352] Set meaningful order in cards with status-indicator

---

src/open_inwoner/utils/ckeditor.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2343
This approach ensures that screen readers can read both the visible link text (inside the a-href anchor) _**and**_ the additional information about the link opening a new/different website, which is information coming from the meaningful icon.

♿ [#2352] Remove faulty aria-label and add external link

---

requirements/base.txt
requirements/ci.txt
requirements/dev.txt

xmlsec has done efforts to support binary wheels together with lxml to avoid compile/installation/runtime issues, which should also speed up installation since no source compilation is required.
Commit message from eeac088fe42ce943dbd904437066c3f9e7c9f830:
Several teammembers have faced sporadic issues installing xmlsec due to missing binaries and the resulting difficulties in building the packages with the right library versions. Requiring at least 1.3.14 allows us to use the pre-built binaries.

:arrow_up: [#2562] Bump lxml and xmlsec to their latest versions

---

src/open_inwoner/templates/pages/cases/statuses.html

icons need to remain hidden for screenreaders (aria-hidden=true) because material-icons and font-awesome etc. do not provide proper meaningful text, so to add meaning we add a span with the visually hidden sr-only class.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2344

♿ [#2344] Add text alternatives for meaningful status-icons

---

src/open_inwoner/templates/master.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2340
Both the header logo and the footer logo need to use the same ALT that can be set in the Admin in the '**mappen**' configuration: http://localhost:8000/admin/filer/folder/
Each image in there (navigate to any in the mappen/directories) has an 'ALT' field that can be set - but when empty the image should just receive value from the Site Name.

♿ [#2340] Header/footer logo use alt from image configuration

---

src/open_inwoner/scss/components/Table/Table.scss
src/open_inwoner/utils/ckeditor.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2347
this issue is about the HTML structure.
Note: design in this issue is not important and will probably change later, this just contains a rudimentary set-up to make better changes possible for the future and some sad code needed to be refactored.

♿ [#2347] Add table-TH style/markup for product pages

---

src/open_inwoner/openzaak/clients.py
src/open_inwoner/openzaak/tests/factories.py
src/open_inwoner/openzaak/tests/test_clients.py

[#2566] Persist originating service on zgw clients
To support multiple zgw backends, we frequently need to determine
which backend to query for which resource. As a first step to
keeping better track of where ZGW objects come from, in this
commit we persist the zgw service used to configure a client
on the client object, so that we can later fetch and persist
this service to facilitate easier target backend resolution.

[#2566] Persist the originating ZGW service on the client

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
Dockerfile
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

Since bumping our lxml/xmlsec requirements, we can utilize
the pre-built binaries and no longer have a need for the
*-dev system packages. Apart from making things leaner,
this also addresses the following issue in python-xmlsec:
https://github.com/xmlsec/python-xmlsec/issues/320
---
Based on https://github.com/open-formulieren/open-forms/pull/4415

[#2568] Remove deprecated lxml/xmlsec dev packages

---

src/open_inwoner/kvk/tests/test_migrations.py
src/open_inwoner/openzaak/tests/test_migrations.py
src/open_inwoner/utils/tests/test_migrations.py

I've had to write a few non-trivial migrations for the multi-ZGW backend work, and I suspect there will be a few more. To keep things consistent and readable, I've expanded the migration testing utility to support both successful and failing migrations.

Support both  successful and failing migrations in the migration test utility

---

src/open_inwoner/scss/components/ReadMore/ReadMore.scss

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2357
This Zoom issue was already solved for just the Tables by #1258 (by making them break on word normally)
so all that was left, is to actually show the overflowing content...
Problem happens for example when zooming in 400% in case of a product-page with an extremely long H1 title, with more than 24 characters without any breaking dashes etc. which will make an overflow dus to its large font-size.
So here the 'readmore' content should only remain hidden when that functionality is toggled.
When 'readmore' is off or toggled 'open', all content should be visible at all zoom-levels.
Note: Scrollbars appearing are OK for accessibility.
We cannot control the use of long words, and words like 'Verkiezingsprogrammalijst' do exist in …

♿ [#2357] Correct product-pages 400% zoom

---

.github/workflows/ci.yml
.github/workflows/code-quality.yml
Dockerfile
requirements/base.txt
requirements/ci.txt
requirements/dev.txt

This reverts commit 701b4026fcff695f7d543a1c41e3112c9ff37769 and 65115502afcd5b0bf073423cfc21adf91d5e7533. These changes worked on CI and Docker, but not on our test server. Rolling back until we can diagnose the issue: in the meantime, this shouldn't block deploys.

Revert lxml/xmlsec/uwsgi version bumps

---

.github/workflows/ci.yml

We have made several previous attempts at running the CI tests in
parallel, which were ultimately reverted because we ran into the
issue described at https://github.com/django/django/pull/17650 and
https://code.djangoproject.com/ticket/32114 (in this repo, see PRs
#1050, #948 and #690.
The Django ticket has been fixed, but will will only be included
in 5.1 onwards, and won't be backported to 4.2.x. However, it seems
the current testsuite no longer fails with the issue reported in the
Django ticket (pickle related errors). It is possible the potentially
failing tests are flaky, but so far we've not run into it during a
handful of parallel runs. This commit will re-enable parallel tests,
and we'll have to see if we run into the same issues again.

[#2589] Run CI tests in parallel

---

src/open_inwoner/templates/master.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2574
Test this on https://live.browserstack.com/ 
(if you have the browserstack local binary set-up working)
NB: if your localhost URL doesn't work, use http://bs-local.com:8000/ 
There are many browser differences on iOS but the meta-tag seems to be the wisest solution here, in order to also turn-off phone-number detection for ALL dynamic content.
it is also possible to add a (very hacky) “zero-width joiner `&zwj;`" or an empty `<span>` in every case-number, but then it would only work for all those individual numbers and not for the rest of the site.
Note to future self: if the user would create a **bookmark** and add the OIP site/icon as an app _to the Home screen_ of the iPhone, then it will open in something that looks …

[#2574] Added format-detection meta-tag for Safari iOS

---

src/open_inwoner/components/templates/components/AnchorMenu/AnchorMenu.html
src/open_inwoner/components/templates/components/Button/Button.html
src/open_inwoner/js/components/anchor-menu/anchor-menu-mobile.js

issue https://taiga.maykinmedia.nl/project/open-inwoner/task/2435 
note: 
- `aria-expanded` only works for the elements that indicate if a **control** is expanded or collapsed.
- `aria-controls` is not a hard requirement, but 'recommended'

♿ [#2435] Add aria-expanded to mobile anchors navigation

---

requirements/base.in

Specifying multiple package versions without separator (comma, semicolon) is deprecated since pip 24.1 (https://pip.pypa.io/en/stable/news/).

Fix specification of multiple package versions

---

Dockerfile
bin/setup_configuration.sh
bin/wait_for_db.sh

- Add the `setup_configuration.sh` script to the docker build, same as openzaak etc, https://github.com/open-zaak/open-zaak/blob/main/bin/setup_configuration.sh

:whale: Add setup_configuration script

---

src/open_inwoner/search/forms.py

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2371 
hidden label text (visible for screenreaders) should start with text from placeholder.
We are adopting the 'Zoeken' example without dots, like on https://gemeente.groningen.nl/

♿ [#2371] Make search label text same as placeholder

---

.github/workflows/ci.yml

Previously our coverage data was imporperly being shipped to codecov on
two accounts:
1. We were not combining the data files from each run of the test matrix
(elastic and main)
2. The main test run was not running with the appropriate --concurrency
flag and thus it was missing out on coverage data due to not taking
into account all test processes.
This commit addresses both issues and ensures codecov receives the
full coverage data file (both runs, all parallel processes).

 [#2593] Fix missing coverage data in codecov

---

src/open_inwoner/questionnaire/tests/test_admin.py

- The test asserted equality of expected + actual list, which is not guaranteed (presumably this is due to parallel tests; it doesn't seem to occur when tests run sequentially)
- Needed are only the weaker assertions about content being/not being included in the form options
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2602

[#2606] Refactor flakey test, use more general assertions

---

src/open_inwoner/scss/components/TabPanel/TabPanel.scss
src/open_inwoner/ssd/admin.py
src/open_inwoner/ssd/client.py
src/open_inwoner/templates/pages/ssd/monthly_reports_list.html
src/open_inwoner/templates/pages/ssd/reports_base.html
src/open_inwoner/templates/pages/ssd/yearly_reports_list.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2577

[#2577] Use CKEditorWidget for SSD help-text fields

---

src/open_inwoner/scss/pdf/_jaaropgave.scss
src/open_inwoner/scss/pdf/_maandspecificatie.scss
src/open_inwoner/ssd/client.py
src/open_inwoner/ssd/templates/jaaropgave.html
src/open_inwoner/ssd/templates/maandspecificatie.html

Taiga: [#2605](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2605)

[#2605] Use NLDS classes for uitkeringen PDF styling

---

src/open_inwoner/js/components/confirmation/index.js
src/open_inwoner/js/components/modal/index.js
src/open_inwoner/js/components/plan-preview/index.js
src/open_inwoner/scss/components/Plan/PlanCreate.scss
src/open_inwoner/scss/components/modal/_modal.scss
src/open_inwoner/templates/master.html
src/open_inwoner/templates/pages/plans/create.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/us/2402
1. accessibility requirement "When a dialog closes, focus returns to the element that invoked the dialog"
2. making sure the Escape button doesn't interfere with closing of the navigation etc.
3. moving the KCM feedback button to bottom of footer for more logical Tab order
Effect:
after closing a modal your Tab focus should land on the button that opened it, meaning you can Tab backward or forward starting from the modal-opening-control button.

♿ [#2583] Make control of modal focusable in the right order

---

package-lock.json
package.json
src/open_inwoner/scss/components/Grid/Grid.scss
src/open_inwoner/scss/components/HeaderGroup/HeaderGroup.scss
src/open_inwoner/scss/components/Profile/_personal-overview.scss
src/open_inwoner/scss/components/Typography/H1.scss
src/open_inwoner/scss/components/Typography/H2.scss
src/open_inwoner/scss/components/Typography/H3.scss
src/open_inwoner/scss/components/Typography/P.scss
src/open_inwoner/scss/components/_index.scss
src/open_inwoner/templates/cms/collaborate/active_plans_plugin.html
src/open_inwoner/templates/cms/plugins/userfeed/userfeed.html
src/open_inwoner/templates/cms/products/categories_plugin.html
src/open_inwoner/templates/pages/category/detail.html
src/open_inwoner/templates/pages/plans/create.html
src/open_inwoner/templates/pages/plans/list.html
src/open_inwoner/templates/pages/profile/contacts/list.html
src/open_inwoner/templates/pages/profile/me.html
src/open_inwoner/templates/pages/profile/mydata.html
src/open_inwoner/templates/pages/questionnaire/questionnaire-step.html

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2584
for a correct screenreader order, interactive elements should not be inside a Heading element.
Connected to PR https://github.com/maykinmedia/open-inwoner-design-tokens/pull/10
Since design-tokens have been updated: $ npm ci --legacy-peer-deps
and $ npm run build

♿ [#2584] Refactor heading architecture (no flexbox)

---

src/open_inwoner/js/components/tab-panels/index.js

issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2508 
Test: http://localhost:8000/accounts/login/ 
If 'zakelijk'/eHerkenning is turned off, then there will be no tab-headers visible, which means no tab-panel Nodes should be rendered 
fixing the console error:
```
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
at new TabPanel (open_inwoner-js.js:4704:24)
at open_inwoner-js.js:4805:10 ...
...
```

:bug: [#2508] Fix hotfix for non-business login tab-panel

---

src/open_inwoner/conf/base.py

Our [notifications-api-common](https://github.com/maykinmedia/notifications-api-common) library interferes with Celery's task loading by patching the autoretry meachanism ([code](https://github.com/maykinmedia/notifications-api-common/blob/main/notifications_api_common/autoretry.py)), which somehow prevents tasks form our apps from showing up in the admin. The temporary fix is to load the library after all our apps.
Eventually needs to be fixed in the library itself.
Taiga: https://taiga.maykinmedia.nl/project/dimpact-enschede-ssc-ict-1/issue/107

[#dimpact-107] Hotfix for celery search task not showing in admin

---

src/open_inwoner/accounts/notifications/tasks.py
src/open_inwoner/accounts/tasks.py

[Taiga #2632](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2632) and [Sentry #1](https://sentry.maykinmedia.nl/organizations/maykin-media/issues/364649), [Sentry #2](https://sentry.maykinmedia.nl/organizations/maykin-media/issues/364650/).
[See also the Celery docs](https://docs.celeryq.dev/en/latest/userguide/tasks.html#avoid-launching-synchronous-subtasks).

[#2432] fix incorrect task invocation in notification processing

---

src/open_inwoner/cms/cases/tests/test_contactform.py
src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/configurations/tests/bootstrap/test_setup_cms.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/tests/factories.py
src/open_inwoner/openzaak/tests/test_case_detail.py

The E-suite occasionally returns case results with descriptions that are longer than allowed by the ZGW spec (20 characters). Updating the E-suite for a single attribute is not an option. The workaround is to store longer descriptions in a dedicated attribute "naam" on `ResultaatType` and use it if it's non-empy, otherwise fall back on default description ("omschrijving"). 
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2640

[#2640] Use separate field for storing long case result descriptions

---

src/open_inwoner/cms/cases/urls.py
src/open_inwoner/cms/cases/views/__init__.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail_redirects.py

The case detail URL now contains a reference to the
ZGW api group to be used to fetch the case. It is quite
likely there are various hard-coded URLs in the wild
(especially in notification emails) that point to the
old case detail URLs. This commit adds a redirect
handler for the now-deprecated case detail URL and
tries to handle the request gracefully, depending on
the case.
[Taiga 2648.](https://taiga.maykinmedia.nl/project/open-inwoner/task/2648)

[#2648] handle legacy case detail URLs with redirect

---

src/open_inwoner/conf/base.py
src/open_inwoner/configurations/tasks.py
src/open_inwoner/configurations/tests/test_emails.py

[Taiga 2657](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2657).

[#2657] migrate send_failed_email_digest cron to Celery

---

src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/tests/mocks.py
src/open_inwoner/userfeed/hooks/external_task.py
src/open_inwoner/userfeed/tests/test_external_tasks.py

The identification number of a related case is shown in the task userfeed, in addition to the task number
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2644

[#2644] Display related case number in task userfeed

---

src/open_inwoner/cms/cases/forms.py
src/open_inwoner/cms/cases/views/cases.py
src/open_inwoner/openzaak/api_models.py
src/open_inwoner/openzaak/tests/test_api_models.py
src/open_inwoner/openzaak/tests/test_cases.py
src/open_inwoner/templates/pages/cases/list_inner.html

Styling for the case filter form is rudimentary and should be improved in accordance with design (see https://taiga.maykinmedia.nl/project/open-inwoner/task/2650)
Taiga: https://github.com/maykinmedia/open-inwoner/pull/new/task/2645-case-filter-status

[#2645] Filter cases by status

---

requirements/base.in
requirements/base.txt
requirements/ci.txt
requirements/dev.txt
src/open_inwoner/openzaak/tests/helpers.py
src/open_inwoner/openzaak/tests/test_migrations.py

zgw-consumers-oas includes tooling for OAS mocks and was deprecated in zgw-consumers 0.33

Bump zgw-consumers to 0.34, install zgw-consumers-oas for tests

---

src/open_inwoner/cms/products/tests/test_plugin_categories.py
src/open_inwoner/pdc/managers.py

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2666

[#2666] Use multiple Zaken API's to filter categories by cases

---

src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/templates/pages/profile/me.html

- Use display name ("roepnaam") in profile welcome message by default
- Use first name as fallback in case roepnaam is not set
- Show roepnaam in profile overview
Taiga: [#2261](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2661), [#2262](https://github.com/maykinmedia/open-inwoner/pull/new/issue/2662-profile-welcome), [#2263](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2663)

[#2261, #2262, #2263] Fix display name in profile

---

src/open_inwoner/accounts/tests/test_file_upload.py
src/open_inwoner/utils/forms.py
src/open_inwoner/utils/tests/test_limited_file_upload_field.py

To allow for better re-use, it is desirable to make the parameters of the field overridable. A case in point is an upcoming change to process ZGW exports, which requires both different size limits and permissible mimetypes.

Make parameters of LimitedUploadFileField overridable

---

src/open_inwoner/openzaak/managers.py
src/open_inwoner/openzaak/models.py
src/open_inwoner/openzaak/tests/factories.py
src/open_inwoner/openzaak/tests/test_models.py

This is a preliminary PR to support the ZGW import/export logic, which will rely on natural keys for (de)serialization.

Implement zgw natural key support

---

src/open_inwoner/js/components/siteimprove/tracking.js

When the `_sz` Array is coming in from SiteImprove, only then should the click events be pushed to that same array.
Done: Commented out Mock (the Mock may have been overwriting the ACTUAL `_sz` object)
- Added console logging in the code to monitor `_sz` interactions.
- Periodically checking the `_sz` object by using a 'poller'.
Network Tab in inspector (use incognito window, accept cookies, disable adblockers):
Open Network tab.
Reload the page.
Filter by "sz" or relevant domain.
Click on relevant requests to inspect.
See:
issue: https://taiga.maykinmedia.nl/project/open-inwoner/us/2124
issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2622

[#2124] Siteimprove interval pause

---

src/open_inwoner/configurations/tasks.py
src/open_inwoner/configurations/tests/test_emails.py
src/open_inwoner/openzaak/tasks.py
src/open_inwoner/openzaak/tests/test_zgw_imports.py
src/open_inwoner/openzaak/tests/test_zgw_imports_task.py
src/open_inwoner/search/tasks.py
src/open_inwoner/search/tests/test_tasks.py

Some of our celery tasks are wrappers around management commands - a legacy feature of the earlier implementation:
- https://github.com/maykinmedia/open-inwoner/blob/develop/src/open_inwoner/configurations/tasks.py
- https://github.com/maykinmedia/open-inwoner/blob/develop/src/open_inwoner/openzaak/tasks.py
- https://github.com/maykinmedia/open-inwoner/blob/develop/src/open_inwoner/search/tasks.py
The PR improves task logging by including the output of the management commands in the celery task results. We decided to keep the commands around for the time being because the libraries we currently use for manually triggering tasks are not maintained, so we may need to make use of the management commands after all.

Refactor celery tasks + management commands

---

src/open_inwoner/search/tests/test_views.py

This commit adds a simple test to ensure we cover the (expectedly) rare case when cases are found in multiple backends. We can't currently cover the error cases well because we silence all client errors. Ideally we'd test this without error-silencing and using VCR, but that's for a later iteration.

Test behavior of case search with multiple results

---

src/open_inwoner/openzaak/management/commands/zgw_import_data.py
src/open_inwoner/openzaak/tests/test_zgw_imports_command.py

Not having a ZGW backend configured is something that happens in the wild, and more broadly, it would be a good thing if the management command does not fail hard on a missing config (as now) but gracefully exits with an error message. Better reporting to users (including our Celery task wrapper for this command), and cuts down on false-positive Sentry pings.

Check for missing ZGW backend config in zgw_import_data command

---

src/open_inwoner/openzaak/tests/test_case_detail.py
src/open_inwoner/openzaak/tests/test_documents.py

The PR adds tests for upload/download of files with multiple documenten backends; the functionality was already implemented.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2230

[#2230] Add tests for document upload/download with multiple backends

---

src/open_inwoner/accounts/signals.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/openklant/api_models.py
src/open_inwoner/openklant/services.py
src/open_inwoner/openklant/tests/data.py
src/open_inwoner/openklant/tests/test_signal.py

Note that this PR also contains a fix for the misnamed `toestemming_zaak_notificaties_alleen_digitaal` on the `Klant` API model (was camel-cased) and some slight refactoring of the hooks for readability and composability.
It might be best to go commit-for-commit: the actual change is in the last commit.

Sync user's notification preferences from klant upon login

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/accounts/tests/test_logging.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/templates/pages/profile/notifications.html

The PR makes the presence of the heading ("choose notifications") contingent on whether any notifications have been enabled by staff users
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2688

[#2688] Improve template for user notifications

---

src/open_inwoner/conf/base.py
src/open_inwoner/conf/dev.py

- The default Django auth backend is not compatible with our practice of (a) using email as username and (b) allowing duplicate emails for DigiD users, because it checks for duplicate emails regardless of login type
- The auth backend overrides in the dev settings are redundant and potentially confusing (in case someone overrides base.py for local testing purposes)
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2698

[#2698] Remove default Django authentication backend

---

src/open_inwoner/conf/dev.py

We were too eager in 65304e2 in removing all the dev backends, in an attempt to avoid divergence between the base and dev authentication backends. Unfortunately, we mistakenly also removed references to the mock backends, which broke local development which suddenly required production settings for DigiD and eHerkenning.
This commit makes more explicit that all we want to do on dev is replace these backends whilst keeping the other settings the same.

Fix missing mock DigiD/eHerkenning backends in dev

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/documents.py
src/open_inwoner/openzaak/notifications.py
src/open_inwoner/openzaak/tests/test_notification_data.py
src/open_inwoner/openzaak/tests/test_notification_utils.py
src/open_inwoner/openzaak/tests/test_notification_zaak_infoobject.py
src/open_inwoner/openzaak/tests/test_notification_zaak_status.py

Support for retrieving zaak notifications from different notification APIs is out of scope for this ticket
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2700

[#2700] Support multiple ZGW backends for zaak notifications

---

src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_profile_views.py

The notification section in the profile did not the admin's choice to enable/disable the relevant notifications. If the admin disabled notifications about "Samenwerken", they would still be listed.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2707

[#2707] Fix display of notification preferences in profile

---

src/open_inwoner/components/templates/components/Form/FileInput.html
src/open_inwoner/scss/components/Actions/Actions.scss
src/open_inwoner/scss/components/Button/Button.scss
src/open_inwoner/scss/components/Card/Card.scss
src/open_inwoner/scss/components/ContactForm/ContactForm.scss
src/open_inwoner/scss/components/Faq/_Faq.scss
src/open_inwoner/scss/components/File/File.scss
src/open_inwoner/scss/components/Filter/Filter.scss
src/open_inwoner/scss/components/Form/FileInput.scss
src/open_inwoner/scss/components/Form/Form.scss
src/open_inwoner/scss/components/Header/PrimaryNavigation.scss
src/open_inwoner/scss/components/MessageFile/MessageFile.scss
src/open_inwoner/scss/components/Notification/_Notification.scss
src/open_inwoner/scss/components/Pagination/Pagination.scss
src/open_inwoner/scss/components/Plan/PlanCreate.scss
src/open_inwoner/scss/components/Plan/PlanEdit.scss
src/open_inwoner/scss/components/PlanTemplate/PlanTemplate.scss
src/open_inwoner/scss/components/Preview/Preview.scss
src/open_inwoner/scss/components/ReadMore/ReadMore.scss
src/open_inwoner/scss/components/TabPanel/TabPanel.scss
src/open_inwoner/scss/components/Table/Table.scss
src/open_inwoner/scss/components/Typography/Link.scss
src/open_inwoner/scss/components/WarningHeader/WarningHeader.scss
src/open_inwoner/scss/overwrites/_ckeditor.scss
src/open_inwoner/templates/pages/cases/document_form.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2703
New design: https://taiga.maykinmedia.nl/project/open-inwoner/task/2702
Main changes in:
src/open_inwoner/templates/pages/cases/document_form.html
src/open_inwoner/components/templates/components/Form/FileInput.html
All the other changes have to do with the very broad **icon font** universal asterisk selector... which was messing up the styles from Buttons that contain the `button--icon-after` class... 
Universal selectors are awful but we might switch to a different icon font at some point in the future, and then these style will be easier to spot/separate.
Test with BSN 111111110: http://localhost:8000/mijn-aanvragen/1/a3c98c9a-d3c9-4f64-9371-9c41fc5781ad/status/

💄 [#2703] Move upload-button for file-input closer to selection field

---

.github/workflows/ci.yml

Apart from housekeeping, this _should_ speed up our setup owing to the switch to `uv`.

Bump setup-django-backend to v1.3

---

src/open_inwoner/cms/cases/tests/test_contactform.py
src/open_inwoner/cms/cases/views/status.py

The creation of contactmomenten without default medewerker was fixed for the standalone contactform, but not for the form embedded in particular zaken.
Taiga:https://taiga.maykinmedia.nl/project/dimpact-enschede-ssc-ict-1/issue/138

[#dimpact-138] Fix creation of contactmoment without medewerker

---

docs/configuration/siteconfig.rst

The PR that introduced the automatic check of setup_configuration docs was merged without rebasing after changes to `SiteConfiguration` had been introduced, hence the failing test.

Update django_setup_configuration docs for SiteConfiguration

---

src/open_inwoner/accounts/forms.py
src/open_inwoner/accounts/templates/accounts/registration_necessary.html
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/templates/pages/profile/notifications.html

https://taiga.maykinmedia.nl/project/open-inwoner/task/2743

[#2743] Show action required notifications only if cases notifications enabled

---

src/open_inwoner/templates/master.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2727
separated from double issue: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2595

♿  [#2727] Correct ALT text of footer logo

---

src/open_inwoner/js/components/map/index.js

feature: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2596
Disables the annoying zoom in the map (leaflet/"Productlocatie Plugin" CMS) on Homepage when you just want to scroll down.
tested in multiple browsers, including on BrowserStack.

[#2596] Disable scroll zoom on Productkaart homepage

---

src/open_inwoner/accounts/models.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/tests/test_user.py
src/open_inwoner/accounts/views/registration.py

Temporary emails created for users who register with kvk, or via oidc must be prevented from prefilling the email field in the `NecessaryUserForm`; the logic for checking this is simplified by using the `has_usable_email` property.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2720

[#2720] Fix email field prefill in NecessaryFieldsUserView

---

src/open_inwoner/accounts/notifications/actions/notify.py
src/open_inwoner/accounts/tests/test_notify_expiring_actions.py

Spurious emails were sent about actions because we did not filter out closed actions.

[#2535] Exclude closed actions from notifications

---

src/open_inwoner/openzaak/import_export.py
src/open_inwoner/openzaak/tests/test_import_export.py

[Taiga issues](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2726).
Essentially, what this does is rewrite all ZGW URLs in the import file to have the same URL root as the service on the target instance (matched on slug).
This is not an especially pretty or general-purpose fix, but it should solve the specific problem for Groningen (who is the only intended user of the feature thus far).

Handle URL rewriting for ZGW import/export

---

src/open_inwoner/accounts/templates/accounts/registration_necessary.html
src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/accounts/views/profile.py
src/open_inwoner/templates/pages/profile/me.html
src/open_inwoner/templates/pages/profile/notifications.html

Hide notifications if disabled via admin:
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2744

[#2744] Hide notifications if disabled via admin

---

src/open_inwoner/accounts/views/profile.py

'Voorkeuren voor meldingen' in de zijbalk van Mijn Profiel, ook als je de meldingen volledig hebt uitgeschakeld
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2759

[#2760] Correct sidebar for when notifications are off

---

src/open_inwoner/openklant/tests/test_contactform.py
src/open_inwoner/openklant/views/contactform.py

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2761

[#2761] Map contact data of anonymous contactmoment to E-suite fields

---

src/open_inwoner/accounts/tests/test_profile_views.py
src/open_inwoner/templates/pages/profile/edit.html

Users should not be able to edit their first name in OIP if the Hall Centraal API is configured to pull data from BRP
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2782 and https://taiga.maykinmedia.nl/project/open-inwoner/issue/2780

[#2782+#2780] Disable first name editing for DigiD user with BRP

---

src/open_inwoner/utils/decorators.py
src/open_inwoner/utils/tests/test_utils.py

We have observed an issue with spurious cache hits in development, that we've been unable to reproduce so far. Looking into this did however prompt an audit of the caching decorator, which reveals we potentially have an issue where a cached "None" value is mis- interpreted as "not cached" rather than "cached as None". This commit clarifies the expected behaviour with a test and a more robust cache check.

Disambiguate missing cache values from None

---

src/open_inwoner/cms/cases/views/services.py

[Taiga 2795](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2795).
These changes are necessary because we do not want a failure to resolve a single case to abort the thread for the whole API group. If one case fails, we should still try and return the cases that properly resolve.

[#2795] More fine-grained error handling in concurrent case fetching

---

src/open_inwoner/openklant/tests/test_contactform.py
src/open_inwoner/openklant/views/contactform.py

[Taiga 2809](https://taiga.maykinmedia.nl/project/open-inwoner/issue/2809).

[#2809] Anonymous contact form should not send empty email or phone

---

.github/workflows/ci.yml

[As per the Playwright docs](https://playwright.dev/python/docs/ci#caching-browsers), caching browsers is not recommended, both because downloading the binary is not much slower, but also because system dependencies are required, and these cannot be cached. Even worse, the system dependencies can become stale as the CI images get upgraded. This seems to have happened recently, with persistent "It looks like you are using Playwright Sync API inside the asyncio loop." errors sporadically appearing (in this case, for webkit only) and this being fixed, without further code changes, by disabling the browser cache.

Disable playwright browser cache in CI

---

src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openzaak/tests/test_case_detail.py

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2823

[#2823] Filter contactmomenten on Mijn Vragen based on kanaal

---

src/open_inwoner/js/components/accessibility/change_font.js

issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2372
Chose to not remove the attributes, but correctly toggle them instead.

♿  [#2372] Fix dyslexia data-attributes for toggling accessible label

---

src/open_inwoner/openklant/models.py
src/open_inwoner/openklant/services.py
src/openklant2/client.py
src/openklant2/tests/helpers.py

[Taiga 2838](https://taiga.maykinmedia.nl/project/open-inwoner/task/2838)

[#2838] Make OpenKlant2 client compatible with zgw_consumers logic

---

src/open_inwoner/accounts/signals.py
src/open_inwoner/accounts/tests/test_auth.py
src/open_inwoner/accounts/views/mixins.py
src/open_inwoner/accounts/views/signals.py
src/open_inwoner/cms/cases/tests/test_contactform.py
src/open_inwoner/cms/cases/tests/test_htmx.py
src/open_inwoner/cms/cases/views/status.py
src/open_inwoner/openklant/clients.py
src/open_inwoner/openklant/models.py
src/open_inwoner/openklant/services.py
src/open_inwoner/openklant/tests/test_openklant2_service.py
src/open_inwoner/openzaak/tests/test_case_detail.py

The `create_klant_for_new_user` and `update_user_from_klant_on_login` signals are coupled to the eSuite klanten API service. The PR introduces service objects which perform the actual fetch/create/update logic. This way we branch on eSuite or OpenKlant2.
Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/task/2820

[#2820] Reduce coupling of user signals and klanten API logic

---

src/open_inwoner/api/search/tests/test_autocomplete_api.py
src/open_inwoner/search/tests/test_search_products_boost.py

These always get in the way of my 100% pass rate when running `python src/manage.py test open_inwoner --exclude-tag=e2e --exclude-tag=elastic` (they pass on the CI main run, which runs with the same flags, because we always have an elasticsearch instance running).

Mark incorrectly untagged elasticsearch tests

---

src/open_inwoner/openklant/api_models.py
src/open_inwoner/openklant/tests/data.py
src/open_inwoner/openklant/tests/test_contactform.py
src/open_inwoner/openklant/views/contactform.py

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2811

[#2811] Exclude empty email/phone number from being sent with contactform

---

.gitignore
docker-compose.yml
docker-init-db.sql
docker-initdb.d/initialize_db.sql

Instead of mounting a script that creates a database user and grants appropriate permission, we set the default database and user to `open_inwoner`, thus ensuring that these are created when the container starts. This facilitates loading in SQL dumps to initialize the container. The dump should be placed in `docker-initdb.d` and is not checked into version control.

Fix support for loading SQL dumps in docker-compose

---

src/open_inwoner/components/templates/components/Header/AccessibilityHeader.html
src/open_inwoner/js/components/accessibility/read.js

Issue: https://taiga.maykinmedia.nl/project/open-inwoner/task/2623
Turns out: the Pause code was in place since the beginning but wrongly implemented since there was no data-attribute,
I also added a stop function on reload because it doesn't make sense to keep on reading a page you're no longer looking at.

♿ [#2623] A11y Fix and add SpeechSynthesis pause/stop functionality

---

src/open_inwoner/conf/parts/case_document_notification.html
src/open_inwoner/conf/parts/case_status_notification.html
src/open_inwoner/conf/parts/case_status_notification_action_required.html
src/open_inwoner/scss/components/AccessibilityHeader/AccessibilityHeader.scss
src/open_inwoner/scss/components/AccessibilitySkipLink/AccessibilitySkipLink.scss
src/open_inwoner/scss/views/_view.scss
src/open_inwoner/static/mailcss/email.css
src/open_inwoner/templates/pages/cases/list_inner.html

Taiga: https://taiga.maykinmedia.nl/project/open-inwoner/issue/2665 
The _turn-numbers-into-phone-links_ feature should be disabled with the format-detection meta-tag, but... on every Safari and iOS update this breaks again 😡; many users on new devices report the meta tag does not solve the problem, so we need to create a hack with pointer-events is zero and add a zero-width joiner `&zwj;` to make the numbers unrecognizable.
I've also added these to the Zaaknummers e-mail templates, since those are also parsed in iOS.
While I was reproducing all this in [Browserstack](https://live.browserstack.com/) I found a bug in the skip-link specific for Safari only, which is also solved here.

:bug: [#2665] Fix phone-parsing Safari (iOS only)
